import type { Content, SkillDef } from './types';
import { ACTS, REGIONS, DUNGEONS } from './world-content';

const skill = (
  id: string,
  name: string,
  effect: SkillDef['effect'],
  element: SkillDef['element'],
  damage: number,
  mana: number,
  cooldown: number,
  range: number,
  radius: number,
  level: number,
  description: string,
): SkillDef => ({
  id,
  name,
  effect,
  element,
  scaling: effect === 'melee' || (effect === 'leap' && damage > 0) ? 'strength' : 'energy',
  pierce: id === 'bonespear',
  slow: element === 'cold' ? 25 : id === 'warcry' ? 30 : 0,
  damage,
  mana,
  cooldown,
  range,
  radius,
  level,
  description,
});
export const BASE_CONTENT: Content = {
  id: 'emberwake',
  version: '2.0.0',
  heroes: [
    {
      id: 'barbarian',
      name: 'Rook',
      className: 'Barbarian',
      attack: 'melee',
      description:
        'A borderland survivor. Close the distance, cleave packs, and turn wounds into endurance.',
      color: '#e4a76a',
      hp: 145,
      mana: 45,
      attributes: { strength: 24, dexterity: 16, vitality: 24, energy: 10 },
      skills: ['cleave', 'leap', 'warcry'],
      weapon: 'axe',
    },
    {
      id: 'sorceress',
      name: 'Mira',
      className: 'Sorceress',
      attack: 'ranged',
      description:
        'The last lantern scholar. Burn from afar, freeze pursuers, and blink through danger.',
      color: '#75cfe7',
      hp: 95,
      mana: 110,
      attributes: { strength: 12, dexterity: 18, vitality: 15, energy: 30 },
      skills: ['firebolt', 'frostnova', 'teleport'],
      weapon: 'staff',
    },
    {
      id: 'necromancer',
      name: 'Silas',
      className: 'Necromancer',
      attack: 'ranged',
      description:
        'Keeper of the unburied. Raise a skeletal escort and curse the debt owed by the living.',
      color: '#afc58a',
      hp: 110,
      mana: 90,
      attributes: { strength: 16, dexterity: 15, vitality: 20, energy: 25 },
      skills: ['bonespear', 'raise', 'curse'],
      weapon: 'wand',
    },
  ],
  skills: [
    skill(
      'cleave',
      'Cleave',
      'melee',
      'physical',
      29,
      7,
      7,
      2.2,
      2.2,
      1,
      'Strike every enemy in reach. Strength increases damage.',
    ),
    skill(
      'leap',
      'Leap strike',
      'leap',
      'physical',
      35,
      12,
      28,
      5,
      1.8,
      2,
      'Vault to a visible landing and strike around it.',
    ),
    skill(
      'warcry',
      'War cry',
      'nova',
      'physical',
      24,
      15,
      35,
      0,
      3.5,
      3,
      'Shock nearby enemies and slow their movement.',
    ),
    skill(
      'firebolt',
      'Fire bolt',
      'projectile',
      'fire',
      27,
      6,
      5,
      10,
      0.25,
      1,
      'A fast burning missile. Energy increases spell damage.',
    ),
    skill(
      'frostnova',
      'Frost nova',
      'nova',
      'cold',
      25,
      14,
      24,
      0,
      3.6,
      2,
      'Freeze a ring of pursuing enemies.',
    ),
    skill(
      'teleport',
      'Teleport',
      'leap',
      'cold',
      0,
      16,
      25,
      6,
      0,
      3,
      'Blink to a visible, clear landing.',
    ),
    skill(
      'bonespear',
      'Bone spear',
      'projectile',
      'physical',
      25,
      7,
      7,
      10,
      0.3,
      1,
      'Pierce a line of enemies with a spectral spear.',
    ),
    skill(
      'raise',
      'Raise skeleton',
      'summon',
      'physical',
      0,
      18,
      18,
      0,
      0,
      2,
      'Consume a slain enemy body to raise an ally. Ranks raise the army limit.',
    ),
    skill(
      'curse',
      'Withering curse',
      'curse',
      'poison',
      12,
      12,
      24,
      7,
      3,
      3,
      'Weaken resistance in an area and inflict poison.',
    ),
  ],
  items: [
    { id: 'axe', name: 'Border axe', slot: 'weapon', damage: 15, armor: 0, width: 2, height: 3 },
    {
      id: 'staff',
      name: 'Lantern staff',
      slot: 'weapon',
      damage: 9,
      armor: 0,
      width: 1,
      height: 4,
    },
    { id: 'wand', name: 'Bone wand', slot: 'weapon', damage: 10, armor: 0, width: 1, height: 2 },
    { id: 'mail', name: 'Pilgrim mail', slot: 'armor', damage: 0, armor: 5, width: 2, height: 3 },
    { id: 'charm', name: 'Seal charm', slot: 'charm', damage: 0, armor: 1, width: 1, height: 1 },
  ],
  monsters: [
    {
      id: 'hound',
      name: 'Ash hound',
      hp: 38,
      damage: 7,
      speed: 2.2,
      range: 1,
      element: 'physical',
      resist: {},
      color: '#ab7860',
      shape: 'beast',
      hazardRadius: 1.8,
      pattern: 'melee',
    },
    {
      id: 'archer',
      name: 'Hollow archer',
      hp: 32,
      damage: 8,
      speed: 1.1,
      range: 6,
      element: 'physical',
      resist: { poison: 0.2 },
      color: '#c3b99b',
      shape: 'skeleton',
      hazardRadius: 1.8,
      pattern: 'ranged',
    },
    {
      id: 'cultist',
      name: 'Cinder acolyte',
      hp: 46,
      damage: 10,
      speed: 1.4,
      range: 6,
      element: 'fire',
      resist: { fire: 0.35 },
      color: '#b3726b',
      shape: 'cultist',
      hazardRadius: 1.8,
      pattern: 'ranged',
    },
    {
      id: 'wraith',
      name: 'Salt wraith',
      hp: 48,
      damage: 9,
      speed: 1.8,
      range: 1.2,
      element: 'cold',
      resist: { cold: 0.4 },
      color: '#91b6be',
      shape: 'skeleton',
      hazardRadius: 1.8,
      pattern: 'melee',
    },
    {
      id: 'demon',
      name: 'Furnace brute',
      hp: 70,
      damage: 13,
      speed: 1.4,
      range: 1.4,
      element: 'physical',
      resist: { fire: 0.4 },
      color: '#c16a4d',
      shape: 'demon',
      hazardRadius: 1.8,
      pattern: 'melee',
    },
    {
      id: 'briar',
      name: 'The Briar Widow',
      hp: 280,
      damage: 19,
      speed: 1.1,
      range: 1.7,
      element: 'poison',
      resist: { poison: 0.45 },
      color: '#a6b665',
      shape: 'beast',
      hazardRadius: 1.8,
      pattern: 'nova',
    },
    {
      id: 'regent',
      name: 'The Glass Regent',
      hp: 320,
      damage: 20,
      speed: 1,
      range: 7,
      element: 'fire',
      resist: { fire: 0.4 },
      color: '#e4bc79',
      shape: 'cultist',
      hazardRadius: 1.8,
      pattern: 'ranged',
    },
    {
      id: 'bellkeeper',
      name: 'The Bellkeeper',
      hp: 360,
      damage: 22,
      speed: 1.1,
      range: 1.6,
      element: 'cold',
      resist: { cold: 0.4 },
      color: '#99b4cf',
      shape: 'skeleton',
      hazardRadius: 1.8,
      pattern: 'summoner',
    },
    {
      id: 'lucent',
      name: 'Lucent, the Unlit King',
      hp: 420,
      damage: 24,
      speed: 1.3,
      range: 1.8,
      element: 'fire',
      resist: { fire: 0.3, poison: 0.25 },
      color: '#ef8662',
      shape: 'demon',
      hazardRadius: 2.4,
      pattern: 'nova',
    },
  ],
  acts: ACTS,
  regions: REGIONS,
  dungeons: DUNGEONS,
};
