import type { Content, SkillDef } from './types';

const skill = (
  id: string,
  name: string,
  effect: SkillDef['effect'],
  element: SkillDef['element'],
  damage: number,
  mana: number,
  cooldown: number,
  range: number,
  radius: number,
  level: number,
  description: string,
): SkillDef => ({
  id,
  name,
  effect,
  element,
  scaling: effect === 'melee' || (effect === 'leap' && damage > 0) ? 'strength' : 'energy',
  pierce: id === 'bonespear',
  slow: element === 'cold' ? 25 : id === 'warcry' ? 30 : 0,
  damage,
  mana,
  cooldown,
  range,
  radius,
  level,
  description,
});
export const BASE_CONTENT: Content = {
  id: 'emberwake',
  version: '1.0.0',
  heroes: [
    {
      id: 'barbarian',
      name: 'Rook',
      className: 'Barbarian',
      attack: 'melee',
      description:
        'A borderland survivor. Close the distance, cleave packs, and turn wounds into endurance.',
      color: '#e4a76a',
      hp: 145,
      mana: 45,
      attributes: { strength: 24, dexterity: 16, vitality: 24, energy: 10 },
      skills: ['cleave', 'leap', 'warcry'],
      weapon: 'axe',
    },
    {
      id: 'sorceress',
      name: 'Mira',
      className: 'Sorceress',
      attack: 'ranged',
      description:
        'The last lantern scholar. Burn from afar, freeze pursuers, and blink through danger.',
      color: '#75cfe7',
      hp: 95,
      mana: 110,
      attributes: { strength: 12, dexterity: 18, vitality: 15, energy: 30 },
      skills: ['firebolt', 'frostnova', 'teleport'],
      weapon: 'staff',
    },
    {
      id: 'necromancer',
      name: 'Silas',
      className: 'Necromancer',
      attack: 'ranged',
      description:
        'Keeper of the unburied. Raise a skeletal escort and curse the debt owed by the living.',
      color: '#afc58a',
      hp: 110,
      mana: 90,
      attributes: { strength: 16, dexterity: 15, vitality: 20, energy: 25 },
      skills: ['bonespear', 'raise', 'curse'],
      weapon: 'wand',
    },
  ],
  skills: [
    skill(
      'cleave',
      'Cleave',
      'melee',
      'physical',
      29,
      7,
      7,
      2.2,
      2.2,
      1,
      'Strike every enemy in reach. Strength increases damage.',
    ),
    skill(
      'leap',
      'Leap strike',
      'leap',
      'physical',
      35,
      12,
      28,
      5,
      1.8,
      2,
      'Vault to a visible landing and strike around it.',
    ),
    skill(
      'warcry',
      'War cry',
      'nova',
      'physical',
      24,
      15,
      35,
      0,
      3.5,
      3,
      'Shock nearby enemies and slow their movement.',
    ),
    skill(
      'firebolt',
      'Fire bolt',
      'projectile',
      'fire',
      27,
      6,
      5,
      10,
      0.25,
      1,
      'A fast burning missile. Energy increases spell damage.',
    ),
    skill(
      'frostnova',
      'Frost nova',
      'nova',
      'cold',
      25,
      14,
      24,
      0,
      3.6,
      2,
      'Freeze a ring of pursuing enemies.',
    ),
    skill(
      'teleport',
      'Teleport',
      'leap',
      'cold',
      0,
      16,
      25,
      6,
      0,
      3,
      'Blink to a visible, clear landing.',
    ),
    skill(
      'bonespear',
      'Bone spear',
      'projectile',
      'physical',
      25,
      7,
      7,
      10,
      0.3,
      1,
      'Pierce a line of enemies with a spectral spear.',
    ),
    skill(
      'raise',
      'Raise skeleton',
      'summon',
      'physical',
      0,
      18,
      18,
      0,
      0,
      2,
      'Consume a slain enemy body to raise an ally. Ranks raise the army limit.',
    ),
    skill(
      'curse',
      'Withering curse',
      'curse',
      'poison',
      12,
      12,
      24,
      7,
      3,
      3,
      'Weaken resistance in an area and inflict poison.',
    ),
  ],
  items: [
    { id: 'axe', name: 'Border axe', slot: 'weapon', damage: 15, armor: 0, width: 2, height: 3 },
    {
      id: 'staff',
      name: 'Lantern staff',
      slot: 'weapon',
      damage: 9,
      armor: 0,
      width: 1,
      height: 4,
    },
    { id: 'wand', name: 'Bone wand', slot: 'weapon', damage: 10, armor: 0, width: 1, height: 2 },
    { id: 'mail', name: 'Pilgrim mail', slot: 'armor', damage: 0, armor: 5, width: 2, height: 3 },
    { id: 'charm', name: 'Seal charm', slot: 'charm', damage: 0, armor: 1, width: 1, height: 1 },
  ],
  monsters: [
    {
      id: 'hound',
      name: 'Ash hound',
      hp: 38,
      damage: 7,
      speed: 2.2,
      range: 1,
      element: 'physical',
      resist: {},
      color: '#ab7860',
      shape: 'beast',
      hazardRadius: 1.8,
      pattern: 'melee',
    },
    {
      id: 'archer',
      name: 'Hollow archer',
      hp: 32,
      damage: 8,
      speed: 1.1,
      range: 6,
      element: 'physical',
      resist: { poison: 0.2 },
      color: '#c3b99b',
      shape: 'skeleton',
      hazardRadius: 1.8,
      pattern: 'ranged',
    },
    {
      id: 'cultist',
      name: 'Cinder acolyte',
      hp: 46,
      damage: 10,
      speed: 1.4,
      range: 6,
      element: 'fire',
      resist: { fire: 0.35 },
      color: '#b3726b',
      shape: 'cultist',
      hazardRadius: 1.8,
      pattern: 'ranged',
    },
    {
      id: 'wraith',
      name: 'Salt wraith',
      hp: 48,
      damage: 9,
      speed: 1.8,
      range: 1.2,
      element: 'cold',
      resist: { cold: 0.4 },
      color: '#91b6be',
      shape: 'skeleton',
      hazardRadius: 1.8,
      pattern: 'melee',
    },
    {
      id: 'demon',
      name: 'Furnace brute',
      hp: 70,
      damage: 13,
      speed: 1.4,
      range: 1.4,
      element: 'physical',
      resist: { fire: 0.4 },
      color: '#c16a4d',
      shape: 'demon',
      hazardRadius: 1.8,
      pattern: 'melee',
    },
    {
      id: 'briar',
      name: 'The Briar Widow',
      hp: 280,
      damage: 19,
      speed: 1.1,
      range: 1.7,
      element: 'poison',
      resist: { poison: 0.45 },
      color: '#a6b665',
      shape: 'beast',
      hazardRadius: 1.8,
      pattern: 'nova',
    },
    {
      id: 'regent',
      name: 'The Glass Regent',
      hp: 320,
      damage: 20,
      speed: 1,
      range: 7,
      element: 'fire',
      resist: { fire: 0.4 },
      color: '#e4bc79',
      shape: 'cultist',
      hazardRadius: 1.8,
      pattern: 'ranged',
    },
    {
      id: 'bellkeeper',
      name: 'The Bellkeeper',
      hp: 360,
      damage: 22,
      speed: 1.1,
      range: 1.6,
      element: 'cold',
      resist: { cold: 0.4 },
      color: '#99b4cf',
      shape: 'skeleton',
      hazardRadius: 1.8,
      pattern: 'summoner',
    },
    {
      id: 'lucent',
      name: 'Lucent, the Unlit King',
      hp: 420,
      damage: 24,
      speed: 1.3,
      range: 1.8,
      element: 'fire',
      resist: { fire: 0.3, poison: 0.25 },
      color: '#ef8662',
      shape: 'demon',
      hazardRadius: 2.4,
      pattern: 'nova',
    },
  ],
  maps: [
    {
      id: 'briarfen',
      name: 'Briarfen',
      subtitle: 'I · The stolen lantern',
      theme: 'marsh',
      introduction:
        'For a century, four lanterns kept the buried king asleep. Last night the fen lantern went dark. Warden Elian sends you to recover its ember before the other lights fail.',
      conclusion:
        'Inside the Widow you find a lantern chain bearing the desert regent’s seal. The theft was planned. Follow the salt road.',
      objective: 'Light both ward stones; defeat the Briar Widow.',
      rooms: [
        [1, 2, 10, 9],
        [8, 6, 17, 12],
        [17, 2, 28, 10],
        [12, 13, 24, 23],
        [25, 12, 39, 26],
        [22, 7, 28, 17],
      ],
      start: { x: 4, y: 5 },
      waypoint: { x: 19, y: 6 },
      exit: { x: 36, y: 24 },
      bossPosition: { x: 34, y: 20 },
      boss: 'briar',
      monsters: ['hound', 'archer'],
      seals: [
        { x: 13, y: 19 },
        { x: 24, y: 5 },
      ],
      chests: [
        { x: 8, y: 4 },
        { x: 21, y: 21 },
      ],
    },
    {
      id: 'saltreach',
      name: 'Saltreach',
      subtitle: 'II · A kingdom of glass',
      theme: 'desert',
      introduction:
        'The salt road ends at a city turned to glass. Its regent traded the second ember for immortality. Two sun obelisks still hold the palace gate shut.',
      conclusion:
        'The Regent shatters. His bargain names the Bellkeeper beneath the monastery, where the lanterns were first forged.',
      objective: 'Kindle the sun obelisks; break the Glass Regent.',
      rooms: [
        [1, 2, 12, 10],
        [9, 7, 17, 23],
        [15, 17, 28, 26],
        [18, 2, 29, 12],
        [14, 6, 22, 10],
        [26, 7, 39, 23],
      ],
      start: { x: 4, y: 5 },
      waypoint: { x: 20, y: 7 },
      exit: { x: 36, y: 20 },
      bossPosition: { x: 34, y: 16 },
      boss: 'regent',
      monsters: ['wraith', 'cultist', 'hound'],
      seals: [
        { x: 12, y: 20 },
        { x: 23, y: 4 },
      ],
      chests: [
        { x: 8, y: 7 },
        { x: 23, y: 23 },
      ],
    },
    {
      id: 'hollowbells',
      name: 'Hollow Bells',
      subtitle: 'III · The debt of the dead',
      theme: 'crypt',
      introduction:
        'The monastery rings with voices of the unburied. The Bellkeeper fed the third ember to the dead. Silence his two funeral bells and take the stair below his altar.',
      conclusion:
        'The bells fall silent. The first wardens did not destroy the king: they imprisoned their own founder. His last ember burns under the world.',
      objective: 'Silence both funeral bells; lay the Bellkeeper to rest.',
      rooms: [
        [1, 2, 11, 10],
        [8, 6, 18, 11],
        [15, 2, 26, 10],
        [12, 8, 17, 22],
        [9, 18, 25, 26],
        [22, 6, 28, 21],
        [26, 15, 39, 26],
      ],
      start: { x: 4, y: 5 },
      waypoint: { x: 19, y: 6 },
      exit: { x: 36, y: 24 },
      bossPosition: { x: 34, y: 21 },
      boss: 'bellkeeper',
      monsters: ['archer', 'wraith', 'cultist'],
      seals: [
        { x: 12, y: 22 },
        { x: 23, y: 4 },
      ],
      chests: [
        { x: 7, y: 4 },
        { x: 20, y: 23 },
      ],
    },
    {
      id: 'firstfurnace',
      name: 'The First Furnace',
      subtitle: 'IV · A light of our own',
      theme: 'inferno',
      introduction:
        'Lucent built the lanterns to steal the world’s dawn. His wardens rebelled, but their prison is breaking. Return the embers to the two furnace anchors and end his claim to the light.',
      conclusion:
        'Lucent falls. You break the lantern chain instead of wearing his crown. Dawn reaches Briarfen, Saltreach, and the quiet monastery. Elian opens the refuge gates. The light belongs to everyone.',
      objective: 'Restore both furnace anchors; defeat Lucent.',
      rooms: [
        [1, 2, 12, 11],
        [9, 7, 18, 23],
        [15, 17, 28, 26],
        [15, 3, 27, 11],
        [23, 7, 30, 21],
        [28, 12, 39, 26],
      ],
      start: { x: 4, y: 5 },
      waypoint: { x: 20, y: 7 },
      exit: { x: 36, y: 24 },
      bossPosition: { x: 34, y: 21 },
      boss: 'lucent',
      monsters: ['demon', 'cultist', 'wraith'],
      seals: [
        { x: 12, y: 20 },
        { x: 23, y: 5 },
      ],
      chests: [
        { x: 8, y: 4 },
        { x: 23, y: 23 },
      ],
    },
  ],
};
