import type { MinionDefinition } from '../domain/types';

/** Two additional recruits per tier, composed entirely from established triggers. */
export const EXPANSION_MINIONS: MinionDefinition[] = [
  {
    id: 'copperbeetle',
    name: 'Copper Beetle',
    symbol: '⚙',
    tier: 1,
    tribe: 'mech',
    attack: 1,
    health: 3,
    text: 'Deathrattle: give your Mechs +1 Attack for this combat.',
    deathrattle: { type: 'buff', tribe: 'mech', attack: 1, health: 0 },
  },
  {
    id: 'bogtoad',
    name: 'Bog Toad',
    symbol: '♞',
    tier: 1,
    tribe: 'beast',
    attack: 1,
    health: 2,
    text: 'Reborn.',
    keywords: ['reborn'],
  },
  {
    id: 'lanternkeeper',
    name: 'Lantern Keeper',
    symbol: '♟',
    tier: 2,
    tribe: 'neutral',
    attack: 2,
    health: 3,
    text: 'Battlecry: gain 1 gold this recruitment.',
    battlecry: { type: 'gold', amount: 1 },
  },
  {
    id: 'tidewisp',
    name: 'Tide Wisp',
    symbol: '✦',
    tier: 2,
    tribe: 'elemental',
    attack: 1,
    health: 5,
    text: 'Taunt. At recruitment end, gain +1 Health permanently.',
    keywords: ['taunt'],
    endTurn: { type: 'self', attack: 0, health: 1 },
  },
  {
    id: 'thornstag',
    name: 'Thorn Stag',
    symbol: '♞',
    tier: 3,
    tribe: 'beast',
    attack: 4,
    health: 4,
    text: 'Taunt. Deathrattle: give your Beasts +1/+2 for this combat.',
    keywords: ['taunt'],
    deathrattle: { type: 'buff', tribe: 'beast', attack: 1, health: 2 },
  },
  {
    id: 'cinderwitch',
    name: 'Cinder Witch',
    symbol: '♜',
    tier: 3,
    tribe: 'demon',
    attack: 3,
    health: 5,
    text: 'Battlecry: give your other Demons +2 Attack permanently.',
    battlecry: { type: 'buff', tribe: 'demon', attack: 2, health: 0 },
  },
  {
    id: 'brassheron',
    name: 'Brass Heron',
    symbol: '⚙',
    tier: 4,
    tribe: 'mech',
    attack: 4,
    health: 5,
    text: 'Windfury. Deathrattle: summon a 2/2 Scrapling.',
    keywords: ['windfury'],
    deathrattle: { type: 'summon', card: 'scrap', count: 1 },
  },
  {
    id: 'mistweaver',
    name: 'Mist Weaver',
    symbol: '✦',
    tier: 4,
    tribe: 'elemental',
    attack: 3,
    health: 7,
    text: 'Whenever you summon another Elemental, give it +3 Health.',
    summonBuff: { tribe: 'elemental', attack: 0, health: 3 },
  },
  {
    id: 'moonmoth',
    name: 'Moon Moth',
    symbol: '♞',
    tier: 5,
    tribe: 'beast',
    attack: 4,
    health: 5,
    text: 'Reborn. Whenever you summon another Beast, give it +2/+2.',
    keywords: ['reborn'],
    summonBuff: { tribe: 'beast', attack: 2, health: 2 },
  },
  {
    id: 'soulbell',
    name: 'Soul Bell',
    symbol: '♜',
    tier: 5,
    tribe: 'demon',
    attack: 3,
    health: 8,
    text: 'Taunt. Whenever a friendly Demon dies in combat, deal 4 damage to a random enemy.',
    keywords: ['taunt'],
    deathDamage: { tribe: 'demon', amount: 4 },
  },
  {
    id: 'stormroc',
    name: 'Storm Roc',
    symbol: '✦',
    tier: 6,
    tribe: 'elemental',
    attack: 8,
    health: 7,
    text: 'Windfury. Deathrattle: deal 6 damage to a random enemy.',
    keywords: ['windfury'],
    deathrattle: { type: 'damage', amount: 6 },
  },
  {
    id: 'ancienttortoise',
    name: 'Ancient Tortoise',
    symbol: '♞',
    tier: 6,
    tribe: 'beast',
    attack: 6,
    health: 12,
    text: 'Taunt. Deathrattle: give all your minions +6 Health for this combat.',
    keywords: ['taunt'],
    deathrattle: { type: 'buff', attack: 0, health: 6 },
  },
];
