import type { HeroDefinition, MinionDefinition, Tribe } from '../domain/types';
type Draft = Omit<MinionDefinition, 'symbol'> & { symbol?: string };
const glyphs: Record<Tribe, string> = {
  beast: '♞',
  mech: '⚙',
  demon: '♜',
  elemental: '✦',
  neutral: '♟',
  all: '✺',
};
const minion = (definition: Draft): MinionDefinition => ({
  symbol: glyphs[definition.tribe],
  ...definition,
});
export const MINIONS: MinionDefinition[] = [
  minion({
    id: 'stray',
    name: 'Briar Stray',
    tier: 1,
    tribe: 'beast',
    attack: 2,
    health: 1,
    text: 'Deathrattle: summon a 1/1 Cub.',
    deathrattle: { type: 'summon', card: 'cub', count: 1 },
  }),
  minion({
    id: 'pup',
    name: 'Clockwork Pup',
    tier: 1,
    tribe: 'mech',
    attack: 2,
    health: 1,
    keywords: ['shield'],
    text: 'Divine Shield.',
  }),
  minion({
    id: 'imp',
    name: 'Coal Imp',
    tier: 1,
    tribe: 'demon',
    attack: 3,
    health: 3,
    text: 'A sturdy start for a demon warband.',
  }),
  minion({
    id: 'spark',
    name: 'Kindle Spark',
    tier: 1,
    tribe: 'elemental',
    attack: 2,
    health: 2,
    text: 'Battlecry: give another friendly minion +1/+1.',
    battlecry: { type: 'buff', attack: 1, health: 1, targeted: true },
  }),
  minion({
    id: 'squire',
    name: 'Hearth Squire',
    tier: 1,
    tribe: 'neutral',
    attack: 1,
    health: 4,
    keywords: ['taunt'],
    text: 'Taunt.',
  }),
  minion({
    id: 'cat',
    name: 'Alley Prowler',
    tier: 1,
    tribe: 'beast',
    attack: 1,
    health: 1,
    text: 'Battlecry: summon a 1/1 Cub.',
    battlecry: { type: 'summon', card: 'cub', count: 1 },
  }),
  minion({
    id: 'leader',
    name: 'Pack Caller',
    tier: 2,
    tribe: 'beast',
    attack: 3,
    health: 3,
    text: 'Whenever you summon another Beast, give it +2 Attack.',
    summonBuff: { tribe: 'beast', attack: 2, health: 0 },
  }),
  minion({
    id: 'harvester',
    name: 'Scrap Harvester',
    tier: 2,
    tribe: 'mech',
    attack: 2,
    health: 4,
    text: 'Deathrattle: summon a 2/2 Scrapling.',
    deathrattle: { type: 'summon', card: 'scrap', count: 1 },
  }),
  minion({
    id: 'matron',
    name: 'Imp Matron',
    tier: 2,
    tribe: 'demon',
    attack: 2,
    health: 5,
    text: 'Deathrattle: summon two 1/1 Wisps.',
    deathrattle: { type: 'summon', card: 'wisp', count: 2 },
  }),
  minion({
    id: 'molten',
    name: 'Molten Pebble',
    tier: 2,
    tribe: 'elemental',
    attack: 3,
    health: 3,
    text: 'At recruitment end, gain +1/+1 permanently.',
    endTurn: { type: 'self', attack: 1, health: 1 },
  }),
  minion({
    id: 'banner',
    name: 'Banner Bearer',
    tier: 2,
    tribe: 'neutral',
    attack: 2,
    health: 3,
    text: 'Battlecry: give another friendly minion +2/+2.',
    battlecry: { type: 'buff', attack: 2, health: 2, targeted: true },
  }),
  minion({
    id: 'hyena',
    name: 'Briar Scavenger',
    tier: 2,
    tribe: 'beast',
    attack: 2,
    health: 3,
    text: 'Whenever a friendly Beast dies in combat, gain +2/+1 for that combat.',
    deathGrowth: { tribe: 'beast', attack: 2, health: 1 },
  }),
  minion({
    id: 'rat',
    name: 'Nest Guardian',
    tier: 3,
    tribe: 'beast',
    attack: 3,
    health: 4,
    text: 'Deathrattle: summon two 1/1 Cubs.',
    deathrattle: { type: 'summon', card: 'cub', count: 2 },
  }),
  minion({
    id: 'cobalt',
    name: 'Cobalt Guardian',
    tier: 3,
    tribe: 'mech',
    attack: 4,
    health: 3,
    keywords: ['shield'],
    text: 'Divine Shield. Whenever you summon another Mech, regain Divine Shield.',
    regainShield: 'mech',
  }),
  minion({
    id: 'juggler',
    name: 'Soul Juggler',
    tier: 3,
    tribe: 'demon',
    attack: 3,
    health: 4,
    text: 'Whenever a friendly Demon dies in combat, deal 3 damage to a random enemy.',
    deathDamage: { tribe: 'demon', amount: 3 },
  }),
  minion({
    id: 'tempest',
    name: 'Young Tempest',
    tier: 3,
    tribe: 'elemental',
    attack: 4,
    health: 3,
    keywords: ['windfury'],
    text: 'Windfury: attacks twice when its turn to attack comes.',
  }),
  minion({
    id: 'captain',
    name: 'Hearth Captain',
    tier: 3,
    tribe: 'neutral',
    attack: 3,
    health: 3,
    text: 'Battlecry: give your other minions +1/+1.',
    battlecry: { type: 'buff', attack: 1, health: 1 },
  }),
  minion({
    id: 'sentinel',
    name: 'Iron Sentinel',
    tier: 3,
    tribe: 'mech',
    attack: 3,
    health: 7,
    keywords: ['taunt'],
    text: 'Taunt.',
  }),
  minion({
    id: 'hydra',
    name: 'Briar Hydra',
    tier: 4,
    tribe: 'beast',
    attack: 3,
    health: 5,
    keywords: ['cleave'],
    text: 'Also damages the minions adjacent to its attack target.',
  }),
  minion({
    id: 'bomb',
    name: 'Clockwork Bomb',
    tier: 4,
    tribe: 'mech',
    attack: 4,
    health: 4,
    text: 'Deathrattle: deal 5 damage to a random enemy.',
    deathrattle: { type: 'damage', amount: 5 },
  }),
  minion({
    id: 'watcher',
    name: 'Pit Watcher',
    tier: 4,
    tribe: 'demon',
    attack: 5,
    health: 6,
    text: 'At recruitment end, gain +1/+1 per other friendly Demon.',
    endTurn: { type: 'perTribe', tribe: 'demon', attack: 1, health: 1 },
  }),
  minion({
    id: 'dancer',
    name: 'Cinder Dancer',
    tier: 4,
    tribe: 'elemental',
    attack: 4,
    health: 4,
    text: 'After you buy an Elemental, give your Elementals +1/+1 permanently.',
    buyBuff: { tribe: 'elemental', attack: 1, health: 1 },
  }),
  minion({
    id: 'menagerie',
    name: 'Menagerie Keeper',
    tier: 4,
    tribe: 'neutral',
    attack: 4,
    health: 4,
    text: 'At recruitment end, give your leftmost Beast, Mech, Demon and Elemental +1/+1.',
    endTurn: { type: 'menagerie', attack: 1, health: 1 },
  }),
  minion({
    id: 'mother',
    name: 'Briar Matriarch',
    tier: 4,
    tribe: 'beast',
    attack: 4,
    health: 5,
    text: 'Whenever you summon another Beast, give it +3/+3.',
    summonBuff: { tribe: 'beast', attack: 3, health: 3 },
  }),
  minion({
    id: 'croc',
    name: 'Ancient Crocolisk',
    tier: 5,
    tribe: 'beast',
    attack: 5,
    health: 6,
    text: 'Deathrattle: give your Beasts +3/+3 for this combat.',
    deathrattle: { type: 'buff', tribe: 'beast', attack: 3, health: 3 },
  }),
  minion({
    id: 'egg',
    name: 'Mechanical Egg',
    tier: 5,
    tribe: 'mech',
    attack: 0,
    health: 5,
    text: 'Deathrattle: summon an 8/8 Iron Drake.',
    deathrattle: { type: 'summon', card: 'drake', count: 1 },
  }),
  minion({
    id: 'infernal',
    name: 'Infernal Herald',
    tier: 5,
    tribe: 'demon',
    attack: 6,
    health: 6,
    text: 'At recruitment end, give your Demons +2 Attack permanently.',
    endTurn: { type: 'tribe', tribe: 'demon', attack: 2, health: 0 },
  }),
  minion({
    id: 'cyclone',
    name: 'Glass Cyclone',
    tier: 5,
    tribe: 'elemental',
    attack: 5,
    health: 6,
    keywords: ['shield', 'windfury'],
    text: 'Divine Shield. Windfury.',
  }),
  minion({
    id: 'baron',
    name: 'Echo Baron',
    tier: 5,
    tribe: 'neutral',
    attack: 1,
    health: 7,
    text: 'Your Deathrattles trigger one extra time while this minion survives. Golden: two extra times.',
    extraDeathrattle: 1,
  }),
  minion({
    id: 'phoenix',
    name: 'Ash Phoenix',
    tier: 5,
    tribe: 'beast',
    attack: 5,
    health: 3,
    keywords: ['reborn'],
    text: 'Reborn: returns once at base stats with 1 Health, without buffs.',
  }),
  minion({
    id: 'wolf',
    name: 'Greatwood Wolf',
    tier: 6,
    tribe: 'beast',
    attack: 7,
    health: 7,
    text: 'Deathrattle: give all friendly minions +4/+4 for this combat.',
    deathrattle: { type: 'buff', attack: 4, health: 4 },
  }),
  minion({
    id: 'reaper',
    name: 'Foe Reaper',
    tier: 6,
    tribe: 'mech',
    attack: 6,
    health: 9,
    keywords: ['cleave'],
    text: 'Also damages the minions adjacent to its attack target.',
  }),
  minion({
    id: 'devourer',
    name: 'Abyssal Patron',
    tier: 6,
    tribe: 'demon',
    attack: 9,
    health: 9,
    text: 'Battlecry: give your other Demons +3/+3.',
    battlecry: { type: 'buff', tribe: 'demon', attack: 3, health: 3 },
  }),
  minion({
    id: 'elder',
    name: 'Mountain Elder',
    tier: 6,
    tribe: 'elemental',
    attack: 6,
    health: 8,
    text: 'At recruitment end, give your Elementals +2/+2 permanently.',
    endTurn: { type: 'tribe', tribe: 'elemental', attack: 2, health: 2 },
  }),
  minion({
    id: 'amalgam',
    name: 'Wild Amalgam',
    tier: 6,
    tribe: 'all',
    attack: 7,
    health: 7,
    keywords: ['poison'],
    text: 'All tribes. Poisonous: any unshielded combat damage it deals is lethal.',
  }),
  minion({
    id: 'colossus',
    name: 'Sunsteel Colossus',
    tier: 6,
    tribe: 'mech',
    attack: 8,
    health: 8,
    keywords: ['shield', 'taunt'],
    text: 'Divine Shield. Taunt.',
  }),
  minion({
    id: 'cub',
    name: 'Briar Cub',
    tier: 1,
    tribe: 'beast',
    attack: 1,
    health: 1,
    text: 'Summoned token. Not in the shared pool.',
    token: true,
  }),
  minion({
    id: 'scrap',
    name: 'Scrapling',
    tier: 1,
    tribe: 'mech',
    attack: 2,
    health: 2,
    text: 'Summoned token. Not in the shared pool.',
    token: true,
  }),
  minion({
    id: 'wisp',
    name: 'Coal Wisp',
    tier: 1,
    tribe: 'demon',
    attack: 1,
    health: 1,
    text: 'Summoned token. Not in the shared pool.',
    token: true,
  }),
  minion({
    id: 'drake',
    name: 'Iron Drake',
    tier: 1,
    tribe: 'mech',
    attack: 8,
    health: 8,
    text: 'Summoned token. Not in the shared pool.',
    token: true,
  }),
];
export const MINION_BY_ID = Object.fromEntries(MINIONS.map((m) => [m.id, m])) as Record<
  string,
  MinionDefinition
>;
export const RECRUITS = MINIONS.filter((m) => !m.token);
export const HEROES: HeroDefinition[] = [
  {
    id: 'forgekeeper',
    name: 'The Forgekeeper',
    symbol: '⚒',
    cost: 1,
    targeted: true,
    text: 'Once per round, pay 1 gold to give a friendly minion +1/+1 permanently.',
  },
  {
    id: 'quartermaster',
    name: 'The Quartermaster',
    symbol: '¢',
    cost: 0,
    targeted: false,
    text: 'Passive: start each recruitment with 1 extra gold (maximum 11).',
  },
  {
    id: 'wildspeaker',
    name: 'The Wildspeaker',
    symbol: '❧',
    cost: 2,
    targeted: false,
    text: 'Once per round, pay 2 gold to give all friendly Beasts +1/+1 permanently.',
  },
];
