import type { MinionDefinition } from '../domain/types';

/** Two recruits per tier, using only established battlecry, combat and recruitment triggers. */
export const NIGHT_MARKET_MINIONS: MinionDefinition[] = [
  {
    id: 'rivetmouse',
    name: 'Rivet Mouse',
    symbol: '⚙',
    tier: 1,
    tribe: 'mech',
    attack: 2,
    health: 2,
    text: 'Battlecry: give your other Mechs +1 Health permanently.',
    battlecry: { type: 'buff', tribe: 'mech', attack: 0, health: 1 },
  },
  {
    id: 'wickimp',
    name: 'Wick Imp',
    symbol: '♜',
    tier: 1,
    tribe: 'demon',
    attack: 1,
    health: 3,
    text: 'Deathrattle: give your Demons +1 Health for this combat.',
    deathrattle: { type: 'buff', tribe: 'demon', attack: 0, health: 1 },
  },
  {
    id: 'streetapothecary',
    name: 'Street Apothecary',
    symbol: '♟',
    tier: 2,
    tribe: 'neutral',
    attack: 3,
    health: 2,
    text: 'Battlecry: give another friendly minion +1/+3 permanently.',
    battlecry: { type: 'buff', attack: 1, health: 3, targeted: true },
  },
  {
    id: 'glassimp',
    name: 'Glass Imp',
    symbol: '♜',
    tier: 2,
    tribe: 'demon',
    attack: 4,
    health: 1,
    text: 'Divine Shield.',
    keywords: ['shield'],
  },
  {
    id: 'coilserpent',
    name: 'Coil Serpent',
    symbol: '⚙',
    tier: 3,
    tribe: 'mech',
    attack: 4,
    health: 5,
    text: 'Whenever you summon another Mech, give it +2 Attack.',
    summonBuff: { tribe: 'mech', attack: 2, health: 0 },
  },
  {
    id: 'nightporter',
    name: 'Night Porter',
    symbol: '♟',
    tier: 3,
    tribe: 'neutral',
    attack: 3,
    health: 6,
    text: 'Taunt. Deathrattle: give all your minions +1 Attack for this combat.',
    keywords: ['taunt'],
    deathrattle: { type: 'buff', attack: 1, health: 0 },
  },
  {
    id: 'furnacescribe',
    name: 'Furnace Scribe',
    symbol: '♜',
    tier: 4,
    tribe: 'demon',
    attack: 4,
    health: 6,
    text: 'Whenever you buy a Demon, give your Demons +1/+1 permanently.',
    buyBuff: { tribe: 'demon', attack: 1, health: 1 },
  },
  {
    id: 'clockworkmanta',
    name: 'Clockwork Manta',
    symbol: '⚙',
    tier: 4,
    tribe: 'mech',
    attack: 4,
    health: 6,
    text: 'Divine Shield. Deathrattle: summon two 2/2 Scraplings.',
    keywords: ['shield'],
    deathrattle: { type: 'summon', card: 'scrap', count: 2 },
  },
  {
    id: 'maskmerchant',
    name: 'Mask Merchant',
    symbol: '♟',
    tier: 5,
    tribe: 'neutral',
    attack: 4,
    health: 7,
    text: 'At recruitment end, give one Beast, Mech, Demon and Elemental +2/+1 permanently. Each minion is chosen at most once.',
    endTurn: { type: 'menagerie', attack: 2, health: 1 },
  },
  {
    id: 'embernotary',
    name: 'Ember Notary',
    symbol: '♜',
    tier: 5,
    tribe: 'demon',
    attack: 5,
    health: 7,
    text: 'Whenever a friendly Demon dies in combat, gain +1/+2 for this combat.',
    deathGrowth: { tribe: 'demon', attack: 1, health: 2 },
  },
  {
    id: 'lanternengine',
    name: 'Lantern Engine',
    symbol: '⚙',
    tier: 6,
    tribe: 'mech',
    attack: 7,
    health: 10,
    text: 'Whenever you summon another Mech, give it +3/+3.',
    summonBuff: { tribe: 'mech', attack: 3, health: 3 },
  },
  {
    id: 'twilightauctioneer',
    name: 'Twilight Auctioneer',
    symbol: '♟',
    tier: 6,
    tribe: 'neutral',
    attack: 5,
    health: 9,
    text: 'Battlecry: gain 2 gold this recruitment. Your Deathrattles trigger one additional time.',
    battlecry: { type: 'gold', amount: 2 },
    extraDeathrattle: 1,
  },
];
