import type { CardDefinition, Effect } from '../domain/types';
const damage = (
  amount: number,
  extra: Omit<Extract<Effect, { type: 'damage' }>, 'type' | 'amount'> = {},
): Effect => ({ type: 'damage', amount, ...extra });
const block = (amount: number): Effect => ({ type: 'block', amount });
const draw = (amount: number): Effect => ({ type: 'draw', amount });
const status = (
  name: 'strength' | 'dexterity' | 'weak' | 'vulnerable',
  amount: number,
  target: 'self' | 'enemy' | 'all' = 'enemy',
): Effect => ({ type: 'status', status: name, amount, target });
const power = (name: Extract<Effect, { type: 'power' }>['power'], amount = 1): Effect => ({
  type: 'power',
  power: name,
  amount,
});
type Draft = Omit<CardDefinition, 'symbol' | 'family' | 'upgradeText' | 'rarity'> &
  Partial<Pick<CardDefinition, 'symbol' | 'family' | 'upgradeText' | 'rarity'>>;
const card = (c: Draft): CardDefinition => ({
  symbol: c.kind === 'attack' ? '⚔' : c.kind === 'power' ? '✦' : '◈',
  family: 'Ironclad',
  rarity: 'common',
  upgradeText: c.text,
  ...c,
});

/** Original Slay the Spire 1 Ironclad identities and effects; curated pool, no cross-class cards. */
export const CARDS: CardDefinition[] = [
  card({
    id: 'strike',
    name: 'Strike',
    kind: 'attack',
    rarity: 'basic',
    cost: 1,
    starter: true,
    target: true,
    text: 'Deal 6 damage.',
    upgradeText: 'Deal 9 damage.',
    effects: [damage(6)],
    upgradedEffects: [damage(9)],
  }),
  card({
    id: 'defend',
    name: 'Defend',
    kind: 'skill',
    rarity: 'basic',
    cost: 1,
    starter: true,
    text: 'Gain 5 Block.',
    upgradeText: 'Gain 8 Block.',
    effects: [block(5)],
    upgradedEffects: [block(8)],
  }),
  card({
    id: 'bash',
    name: 'Bash',
    kind: 'attack',
    rarity: 'basic',
    cost: 2,
    starter: true,
    target: true,
    text: 'Deal 8 damage. Apply 2 Vulnerable.',
    upgradeText: 'Deal 10 damage. Apply 3 Vulnerable.',
    effects: [damage(8), status('vulnerable', 2)],
    upgradedEffects: [damage(10), status('vulnerable', 3)],
  }),
  card({
    id: 'anger',
    name: 'Anger',
    kind: 'attack',
    cost: 0,
    target: true,
    text: 'Deal 6 damage. Copy this card into discard.',
    upgradeText: 'Deal 8 damage. Copy this card into discard.',
    effects: [
      damage(6),
      { type: 'generate', card: 'anger', amount: 1, zone: 'discard', copySource: true },
    ],
    upgradedEffects: [
      damage(8),
      { type: 'generate', card: 'anger', amount: 1, zone: 'discard', copySource: true },
    ],
  }),
  card({
    id: 'bodySlam',
    name: 'Body Slam',
    kind: 'attack',
    cost: 1,
    upgradedCost: 0,
    target: true,
    family: 'Block',
    text: 'Attack for your current Block.',
    upgradeText: 'Costs 0. Attack for your current Block.',
    effects: [damage(0, { fromBlock: true })],
  }),
  card({
    id: 'clash',
    name: 'Clash',
    kind: 'attack',
    cost: 0,
    target: true,
    onlyAttacks: true,
    text: 'Playable only with no non-Attacks in hand. Deal 14 damage.',
    upgradeText: 'Same restriction. Deal 18 damage.',
    effects: [damage(14)],
    upgradedEffects: [damage(18)],
  }),
  card({
    id: 'cleave',
    name: 'Cleave',
    kind: 'attack',
    cost: 1,
    text: 'Deal 8 damage to every enemy.',
    upgradeText: 'Deal 11 damage to every enemy.',
    effects: [damage(8, { all: true })],
    upgradedEffects: [damage(11, { all: true })],
  }),
  card({
    id: 'clothesline',
    name: 'Clothesline',
    kind: 'attack',
    cost: 2,
    target: true,
    text: 'Deal 12 damage. Apply 2 Weak.',
    upgradeText: 'Deal 14 damage. Apply 3 Weak.',
    effects: [damage(12), status('weak', 2)],
    upgradedEffects: [damage(14), status('weak', 3)],
  }),
  card({
    id: 'flex',
    name: 'Flex',
    kind: 'skill',
    cost: 0,
    family: 'Strength',
    text: 'Gain 2 Strength until turn end.',
    upgradeText: 'Gain 4 Strength until turn end.',
    effects: [{ type: 'temporary', stat: 'strength', amount: 2 }],
    upgradedEffects: [{ type: 'temporary', stat: 'strength', amount: 4 }],
  }),
  card({
    id: 'headbutt',
    name: 'Headbutt',
    kind: 'attack',
    cost: 1,
    target: true,
    family: 'Draw',
    text: 'Deal 9 damage. Put a chosen discarded card on top of draw.',
    upgradeText: 'Deal 12 damage. Put a chosen discarded card on top of draw.',
    effects: [damage(9), { type: 'choose', action: 'topdeck' }],
    upgradedEffects: [damage(12), { type: 'choose', action: 'topdeck' }],
  }),
  card({
    id: 'heavyBlade',
    name: 'Heavy Blade',
    kind: 'attack',
    cost: 2,
    target: true,
    family: 'Strength',
    text: 'Deal 14 damage; Strength contributes 3 times.',
    upgradeText: 'Deal 14 damage; Strength contributes 5 times.',
    effects: [damage(14, { strengthScale: 3 })],
    upgradedEffects: [damage(14, { strengthScale: 5 })],
  }),
  card({
    id: 'ironWave',
    name: 'Iron Wave',
    kind: 'attack',
    cost: 1,
    target: true,
    text: 'Gain 5 Block. Deal 5 damage.',
    upgradeText: 'Gain 7 Block. Deal 7 damage.',
    effects: [block(5), damage(5)],
    upgradedEffects: [block(7), damage(7)],
  }),
  card({
    id: 'perfectedStrike',
    name: 'Perfected Strike',
    kind: 'attack',
    cost: 2,
    target: true,
    text: 'Deal 6 damage plus 2 per Strike card in your combat deck.',
    upgradeText: 'Deal 6 damage plus 3 per Strike card.',
    effects: [damage(6, { strikeScale: 2 })],
    upgradedEffects: [damage(6, { strikeScale: 3 })],
  }),
  card({
    id: 'pommelStrike',
    name: 'Pommel Strike',
    kind: 'attack',
    cost: 1,
    target: true,
    family: 'Draw',
    text: 'Deal 9 damage. Draw 1.',
    upgradeText: 'Deal 10 damage. Draw 2.',
    effects: [damage(9), draw(1)],
    upgradedEffects: [damage(10), draw(2)],
  }),
  card({
    id: 'shrugItOff',
    name: 'Shrug It Off',
    kind: 'skill',
    cost: 1,
    family: 'Block',
    text: 'Gain 8 Block. Draw 1.',
    upgradeText: 'Gain 11 Block. Draw 1.',
    effects: [block(8), draw(1)],
    upgradedEffects: [block(11), draw(1)],
  }),
  card({
    id: 'swordBoomerang',
    name: 'Sword Boomerang',
    kind: 'attack',
    cost: 1,
    family: 'Strength',
    text: 'Deal 3 damage to a random enemy 3 times.',
    upgradeText: 'Deal 3 damage to a random enemy 4 times.',
    effects: [damage(3, { hits: 3, random: true })],
    upgradedEffects: [damage(3, { hits: 4, random: true })],
  }),
  card({
    id: 'thunderclap',
    name: 'Thunderclap',
    kind: 'attack',
    cost: 1,
    text: 'Deal 4 damage and apply 1 Vulnerable to every enemy.',
    upgradeText: 'Deal 7 damage and apply 1 Vulnerable to every enemy.',
    effects: [damage(4, { all: true }), status('vulnerable', 1, 'all')],
    upgradedEffects: [damage(7, { all: true }), status('vulnerable', 1, 'all')],
  }),
  card({
    id: 'trueGrit',
    name: 'True Grit',
    kind: 'skill',
    cost: 1,
    family: 'Exhaust',
    text: 'Gain 7 Block. Exhaust a random card from hand.',
    upgradeText: 'Gain 9 Block. Choose a hand card to Exhaust.',
    effects: [block(7), { type: 'choose', action: 'exhaust', random: true }],
    upgradedEffects: [block(9), { type: 'choose', action: 'exhaust' }],
  }),
  card({
    id: 'twinStrike',
    name: 'Twin Strike',
    kind: 'attack',
    cost: 1,
    target: true,
    family: 'Strength',
    text: 'Deal 5 damage twice.',
    upgradeText: 'Deal 7 damage twice.',
    effects: [damage(5, { hits: 2 })],
    upgradedEffects: [damage(7, { hits: 2 })],
  }),
  card({
    id: 'wildStrike',
    name: 'Wild Strike',
    kind: 'attack',
    cost: 1,
    target: true,
    text: 'Deal 12 damage. Shuffle a Wound into draw.',
    upgradeText: 'Deal 17 damage. Shuffle a Wound into draw.',
    effects: [damage(12), { type: 'generate', card: 'wound', amount: 1, zone: 'draw' }],
    upgradedEffects: [damage(17), { type: 'generate', card: 'wound', amount: 1, zone: 'draw' }],
  }),
  card({
    id: 'battleTrance',
    name: 'Battle Trance',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 0,
    family: 'Draw',
    text: 'Draw 3, then prevent further draw this turn.',
    upgradeText: 'Draw 4, then prevent further draw this turn.',
    effects: [draw(3), { type: 'noDraw' }],
    upgradedEffects: [draw(4), { type: 'noDraw' }],
  }),
  card({
    id: 'bloodletting',
    name: 'Bloodletting',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 0,
    text: 'Lose 3 HP. Gain 2 Energy.',
    upgradeText: 'Lose 3 HP. Gain 3 Energy.',
    effects: [
      { type: 'loseHp', amount: 3 },
      { type: 'energy', amount: 2 },
    ],
    upgradedEffects: [
      { type: 'loseHp', amount: 3 },
      { type: 'energy', amount: 3 },
    ],
  }),
  card({
    id: 'burningPact',
    name: 'Burning Pact',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 1,
    family: 'Exhaust',
    text: 'Choose a card to Exhaust, then draw 2.',
    upgradeText: 'Choose a card to Exhaust, then draw 3.',
    effects: [{ type: 'choose', action: 'exhaust' }, draw(2)],
    upgradedEffects: [{ type: 'choose', action: 'exhaust' }, draw(3)],
  }),
  card({
    id: 'carnage',
    name: 'Carnage',
    kind: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: true,
    ethereal: true,
    text: 'Ethereal. Deal 20 damage.',
    upgradeText: 'Ethereal. Deal 28 damage.',
    effects: [damage(20)],
    upgradedEffects: [damage(28)],
  }),
  card({
    id: 'combust',
    name: 'Combust',
    kind: 'power',
    rarity: 'uncommon',
    cost: 1,
    text: 'Each turn end: lose 1 HP, deal 5 damage to every enemy.',
    upgradeText: 'Each turn end: lose 1 HP, deal 7 damage to every enemy.',
    effects: [power('combust', 5), power('combustHp', 1)],
    upgradedEffects: [power('combust', 7), power('combustHp', 1)],
  }),
  card({
    id: 'darkEmbrace',
    name: 'Dark Embrace',
    kind: 'power',
    rarity: 'uncommon',
    cost: 2,
    upgradedCost: 1,
    family: 'Exhaust',
    text: 'Whenever a card Exhausts, draw 1.',
    upgradeText: 'Costs 1. Whenever a card Exhausts, draw 1.',
    effects: [power('darkEmbrace')],
  }),
  card({
    id: 'disarm',
    name: 'Disarm',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 1,
    target: true,
    exhaust: true,
    text: 'Enemy loses 2 Strength. Exhaust.',
    upgradeText: 'Enemy loses 3 Strength. Exhaust.',
    effects: [status('strength', -2)],
    upgradedEffects: [status('strength', -3)],
  }),
  card({
    id: 'entrench',
    name: 'Entrench',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 2,
    upgradedCost: 1,
    family: 'Block',
    text: 'Double your current Block.',
    upgradeText: 'Costs 1. Double your current Block.',
    effects: [{ type: 'doubleBlock' }],
  }),
  card({
    id: 'feelNoPain',
    name: 'Feel No Pain',
    kind: 'power',
    rarity: 'uncommon',
    cost: 1,
    family: 'Exhaust',
    text: 'Whenever a card Exhausts, gain 3 Block.',
    upgradeText: 'Whenever a card Exhausts, gain 4 Block.',
    effects: [power('feelNoPain', 3)],
    upgradedEffects: [power('feelNoPain', 4)],
  }),
  card({
    id: 'fireBreathing',
    name: 'Fire Breathing',
    kind: 'power',
    rarity: 'uncommon',
    cost: 1,
    text: 'Drawing a Status or Curse deals 6 damage to every enemy.',
    upgradeText: 'Drawing a Status or Curse deals 10 damage to every enemy.',
    effects: [power('fireBreathing', 6)],
    upgradedEffects: [power('fireBreathing', 10)],
  }),
  card({
    id: 'flameBarrier',
    name: 'Flame Barrier',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 2,
    family: 'Block',
    text: 'Gain 12 Block. Until next turn, retaliate for 4 per enemy attack hit.',
    upgradeText: 'Gain 16 Block. Retaliate for 6 per hit.',
    effects: [block(12), { type: 'temporary', stat: 'flameBarrier', amount: 4 }],
    upgradedEffects: [block(16), { type: 'temporary', stat: 'flameBarrier', amount: 6 }],
  }),
  card({
    id: 'ghostlyArmor',
    name: 'Ghostly Armor',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 1,
    ethereal: true,
    text: 'Ethereal. Gain 10 Block.',
    upgradeText: 'Ethereal. Gain 13 Block.',
    effects: [block(10)],
    upgradedEffects: [block(13)],
  }),
  card({
    id: 'hemokinesis',
    name: 'Hemokinesis',
    kind: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: true,
    text: 'Lose 2 HP. Deal 15 damage.',
    upgradeText: 'Lose 2 HP. Deal 20 damage.',
    effects: [{ type: 'loseHp', amount: 2 }, damage(15)],
    upgradedEffects: [{ type: 'loseHp', amount: 2 }, damage(20)],
  }),
  card({
    id: 'inflame',
    name: 'Inflame',
    kind: 'power',
    rarity: 'uncommon',
    cost: 1,
    family: 'Strength',
    text: 'Gain 2 Strength for this combat.',
    upgradeText: 'Gain 3 Strength for this combat.',
    effects: [status('strength', 2, 'self')],
    upgradedEffects: [status('strength', 3, 'self')],
  }),
  card({
    id: 'intimidate',
    name: 'Intimidate',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 0,
    exhaust: true,
    text: 'Apply 1 Weak to every enemy. Exhaust.',
    upgradeText: 'Apply 2 Weak to every enemy. Exhaust.',
    effects: [status('weak', 1, 'all')],
    upgradedEffects: [status('weak', 2, 'all')],
  }),
  card({
    id: 'metallicize',
    name: 'Metallicize',
    kind: 'power',
    rarity: 'uncommon',
    cost: 1,
    family: 'Block',
    text: 'At turn end, gain 3 Block.',
    upgradeText: 'At turn end, gain 4 Block.',
    effects: [power('metallicize', 3)],
    upgradedEffects: [power('metallicize', 4)],
  }),
  card({
    id: 'powerThrough',
    name: 'Power Through',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 1,
    family: 'Block',
    text: 'Add 2 Wounds to hand. Gain 15 Block.',
    upgradeText: 'Add 2 Wounds to hand. Gain 20 Block.',
    effects: [{ type: 'generate', card: 'wound', amount: 2, zone: 'hand' }, block(15)],
    upgradedEffects: [{ type: 'generate', card: 'wound', amount: 2, zone: 'hand' }, block(20)],
  }),
  card({
    id: 'pummel',
    name: 'Pummel',
    kind: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: true,
    exhaust: true,
    family: 'Strength',
    text: 'Deal 2 damage 4 times. Exhaust.',
    upgradeText: 'Deal 2 damage 5 times. Exhaust.',
    effects: [damage(2, { hits: 4 })],
    upgradedEffects: [damage(2, { hits: 5 })],
  }),
  card({
    id: 'rage',
    name: 'Rage',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 0,
    family: 'Block',
    text: 'For this turn, playing an Attack gives 3 Block.',
    upgradeText: 'For this turn, playing an Attack gives 5 Block.',
    effects: [{ type: 'temporary', stat: 'rage', amount: 3 }],
    upgradedEffects: [{ type: 'temporary', stat: 'rage', amount: 5 }],
  }),
  card({
    id: 'rupture',
    name: 'Rupture',
    kind: 'power',
    rarity: 'uncommon',
    cost: 1,
    text: 'Losing HP to a card grants 1 Strength.',
    upgradeText: 'Losing HP to a card grants 2 Strength.',
    effects: [power('rupture', 1)],
    upgradedEffects: [power('rupture', 2)],
  }),
  card({
    id: 'secondWind',
    name: 'Second Wind',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 1,
    family: 'Exhaust',
    text: 'Exhaust non-Attacks in hand. Gain 5 Block per card.',
    upgradeText: 'Exhaust non-Attacks in hand. Gain 7 Block per card.',
    effects: [{ type: 'exhaustHand', nonAttacks: true, blockEach: 5 }],
    upgradedEffects: [{ type: 'exhaustHand', nonAttacks: true, blockEach: 7 }],
  }),
  card({
    id: 'seeingRed',
    name: 'Seeing Red',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 1,
    upgradedCost: 0,
    exhaust: true,
    text: 'Gain 2 Energy. Exhaust.',
    upgradeText: 'Costs 0. Gain 2 Energy. Exhaust.',
    effects: [{ type: 'energy', amount: 2 }],
  }),
  card({
    id: 'sentinel',
    name: 'Sentinel',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 1,
    family: 'Exhaust',
    text: 'Gain 5 Block. When Exhausted, gain 2 Energy.',
    upgradeText: 'Gain 8 Block. When Exhausted, gain 3 Energy.',
    effects: [block(5)],
    upgradedEffects: [block(8)],
  }),
  card({
    id: 'shockwave',
    name: 'Shockwave',
    kind: 'skill',
    rarity: 'uncommon',
    cost: 2,
    exhaust: true,
    text: 'Apply 3 Weak and 3 Vulnerable to every enemy. Exhaust.',
    upgradeText: 'Apply 5 Weak and 5 Vulnerable to every enemy. Exhaust.',
    effects: [status('weak', 3, 'all'), status('vulnerable', 3, 'all')],
    upgradedEffects: [status('weak', 5, 'all'), status('vulnerable', 5, 'all')],
  }),
  card({
    id: 'uppercut',
    name: 'Uppercut',
    kind: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: true,
    text: 'Deal 13 damage. Apply 1 Weak and 1 Vulnerable.',
    upgradeText: 'Deal 13 damage. Apply 2 Weak and 2 Vulnerable.',
    effects: [damage(13), status('weak', 1), status('vulnerable', 1)],
    upgradedEffects: [damage(13), status('weak', 2), status('vulnerable', 2)],
  }),
  card({
    id: 'whirlwind',
    name: 'Whirlwind',
    kind: 'attack',
    rarity: 'uncommon',
    cost: -2,
    family: 'Strength',
    text: 'Spend all Energy. Deal 5 damage to every enemy X times.',
    upgradeText: 'Spend all Energy. Deal 8 damage to every enemy X times.',
    effects: [damage(5, { all: true, xHits: true })],
    upgradedEffects: [damage(8, { all: true, xHits: true })],
  }),
  card({
    id: 'barricade',
    name: 'Barricade',
    kind: 'power',
    rarity: 'rare',
    cost: 3,
    upgradedCost: 2,
    family: 'Block',
    text: 'Keep Block between turns.',
    upgradeText: 'Costs 2. Keep Block between turns.',
    effects: [power('barricade')],
  }),
  card({
    id: 'bludgeon',
    name: 'Bludgeon',
    kind: 'attack',
    rarity: 'rare',
    cost: 3,
    target: true,
    text: 'Deal 32 damage.',
    upgradeText: 'Deal 42 damage.',
    effects: [damage(32)],
    upgradedEffects: [damage(42)],
  }),
  card({
    id: 'corruption',
    name: 'Corruption',
    kind: 'power',
    rarity: 'rare',
    cost: 3,
    upgradedCost: 2,
    family: 'Exhaust',
    text: 'Skills cost 0 and Exhaust when played.',
    upgradeText: 'Costs 2. Skills cost 0 and Exhaust when played.',
    effects: [power('corruption')],
  }),
  card({
    id: 'demonForm',
    name: 'Demon Form',
    kind: 'power',
    rarity: 'rare',
    cost: 3,
    family: 'Strength',
    text: 'At each future turn start, gain 2 Strength.',
    upgradeText: 'At each future turn start, gain 3 Strength.',
    effects: [power('demonForm', 2)],
    upgradedEffects: [power('demonForm', 3)],
  }),
  card({
    id: 'feed',
    name: 'Feed',
    kind: 'attack',
    rarity: 'rare',
    cost: 1,
    target: true,
    exhaust: true,
    text: 'Deal 10 damage. A fatal hit on a non-minion grants 3 max HP. Exhaust.',
    upgradeText: 'Deal 12 damage. Fatal grants 4 max HP. Exhaust.',
    effects: [damage(10, { fatalMaxHp: 3 })],
    upgradedEffects: [damage(12, { fatalMaxHp: 4 })],
  }),
  card({
    id: 'fiendFire',
    name: 'Fiend Fire',
    kind: 'attack',
    rarity: 'rare',
    cost: 2,
    target: true,
    exhaust: true,
    family: 'Exhaust',
    text: 'Exhaust the rest of your hand; deal 7 damage per card. Exhaust.',
    upgradeText: 'Exhaust the rest of your hand; deal 10 damage per card. Exhaust.',
    effects: [{ type: 'exhaustHand', damageEach: 7 }],
    upgradedEffects: [{ type: 'exhaustHand', damageEach: 10 }],
  }),
  card({
    id: 'immolate',
    name: 'Immolate',
    kind: 'attack',
    rarity: 'rare',
    cost: 2,
    text: 'Deal 21 damage to every enemy. Add a Burn to discard.',
    upgradeText: 'Deal 28 damage to every enemy. Add a Burn to discard.',
    effects: [
      damage(21, { all: true }),
      { type: 'generate', card: 'burn', amount: 1, zone: 'discard' },
    ],
    upgradedEffects: [
      damage(28, { all: true }),
      { type: 'generate', card: 'burn', amount: 1, zone: 'discard' },
    ],
  }),
  card({
    id: 'impervious',
    name: 'Impervious',
    kind: 'skill',
    rarity: 'rare',
    cost: 2,
    exhaust: true,
    family: 'Block',
    text: 'Gain 30 Block. Exhaust.',
    upgradeText: 'Gain 40 Block. Exhaust.',
    effects: [block(30)],
    upgradedEffects: [block(40)],
  }),
  card({
    id: 'limitBreak',
    name: 'Limit Break',
    kind: 'skill',
    rarity: 'rare',
    cost: 1,
    exhaust: true,
    upgradedExhaust: false,
    family: 'Strength',
    text: 'Double your Strength. Exhaust.',
    upgradeText: 'Double your Strength. Does not Exhaust.',
    effects: [{ type: 'doubleStrength' }],
  }),
  card({
    id: 'offering',
    name: 'Offering',
    kind: 'skill',
    rarity: 'rare',
    cost: 0,
    exhaust: true,
    family: 'Draw',
    text: 'Lose 6 HP. Gain 2 Energy. Draw 3. Exhaust.',
    upgradeText: 'Lose 6 HP. Gain 2 Energy. Draw 5. Exhaust.',
    effects: [{ type: 'loseHp', amount: 6 }, { type: 'energy', amount: 2 }, draw(3)],
    upgradedEffects: [{ type: 'loseHp', amount: 6 }, { type: 'energy', amount: 2 }, draw(5)],
  }),
  card({
    id: 'reaper',
    name: 'Reaper',
    kind: 'attack',
    rarity: 'rare',
    cost: 2,
    exhaust: true,
    text: 'Deal 4 damage to every enemy. Heal HP equal to unblocked damage. Exhaust.',
    upgradeText: 'Deal 5 damage to every enemy. Heal unblocked damage. Exhaust.',
    effects: [damage(4, { all: true, heal: true })],
    upgradedEffects: [damage(5, { all: true, heal: true })],
  }),
  card({
    id: 'dazed',
    name: 'Dazed',
    kind: 'status',
    rarity: 'special',
    cost: -1,
    token: true,
    ethereal: true,
    text: 'Unplayable. Ethereal: Exhaust at turn end.',
    effects: [],
  }),
  card({
    id: 'wound',
    name: 'Wound',
    kind: 'status',
    rarity: 'special',
    cost: -1,
    token: true,
    text: 'Unplayable. A dead draw until discarded or Exhausted.',
    effects: [],
  }),
  card({
    id: 'burn',
    name: 'Burn',
    kind: 'status',
    rarity: 'special',
    cost: -1,
    token: true,
    text: 'Unplayable. At turn end, take 2 damage (Block applies).',
    effects: [],
  }),
  card({
    id: 'slimed',
    name: 'Slimed',
    kind: 'status',
    rarity: 'special',
    cost: 1,
    token: true,
    exhaust: true,
    text: 'Exhaust. Spend energy to remove it from this fight.',
    effects: [],
  }),
  card({
    id: 'injury',
    name: 'Injury',
    kind: 'curse',
    rarity: 'special',
    cost: -1,
    token: true,
    text: 'Unplayable. Remains in your permanent deck until removed.',
    effects: [],
  }),
  card({
    id: 'regret',
    name: 'Regret',
    kind: 'curse',
    rarity: 'special',
    cost: -1,
    token: true,
    text: 'Unplayable. At turn end, lose HP equal to your hand size.',
    effects: [],
  }),
];
export const CARD_BY_ID = Object.fromEntries(CARDS.map((c) => [c.id, c])) as Record<
  string,
  CardDefinition
>;
export const REWARD_CARDS = CARDS.filter((c) => !c.starter && !c.token);
export const cardCost = (id: string, upgraded: boolean) =>
  upgraded ? (CARD_BY_ID[id].upgradedCost ?? CARD_BY_ID[id].cost) : CARD_BY_ID[id].cost;
