import type { CardDefinition, Effect } from '../domain/types';

type Draft = Omit<CardDefinition, 'character' | 'symbol' | 'family' | 'rarity' | 'upgradeText'> &
  Partial<Pick<CardDefinition, 'symbol' | 'family' | 'rarity' | 'upgradeText'>>;
const card = (d: Draft): CardDefinition => ({
  character: 'silent',
  symbol: d.kind === 'attack' ? '†' : '◈',
  family: 'Silent',
  rarity: 'common',
  upgradeText: d.text,
  ...d,
});
const hit = (amount: number, all = false): Effect => ({ type: 'damage', amount, all });
const block = (amount: number): Effect => ({ type: 'block', amount });
const draw = (amount: number): Effect => ({ type: 'draw', amount });
const poison = (amount: number, all = false): Effect => ({
  type: 'status',
  status: 'poison',
  amount,
  target: all ? 'all' : 'enemy',
});
const weak = (amount: number, all = false): Effect => ({
  type: 'status',
  status: 'weak',
  amount,
  target: all ? 'all' : 'enemy',
});
const discard = (count = 1): Effect => ({ type: 'choose', action: 'discard', count });
const shivs = (amount: number): Effect => ({
  type: 'generate',
  card: 'shiv',
  amount,
  zone: 'hand',
});
const energy = (amount: number): Effect => ({ type: 'energy', amount });
const power = (name: Extract<Effect, { type: 'power' }>['power'], amount: number): Effect => ({
  type: 'power',
  power: name,
  amount,
});

/** Curated original Silent cards. Effects are declarative; discard choices resolve in the domain. */
export const SILENT_CARDS: CardDefinition[] = [
  card({
    id: 'neutralize',
    name: 'Neutralize',
    kind: 'attack',
    rarity: 'basic',
    starter: true,
    cost: 0,
    target: true,
    text: 'Deal 3 damage. Apply 1 Weak.',
    upgradeText: 'Deal 4 damage. Apply 2 Weak.',
    effects: [hit(3), weak(1)],
    upgradedEffects: [hit(4), weak(2)],
  }),
  card({
    id: 'survivor',
    name: 'Survivor',
    kind: 'skill',
    rarity: 'basic',
    starter: true,
    cost: 1,
    text: 'Gain 8 Block. Discard 1 card.',
    upgradeText: 'Gain 11 Block. Discard 1 card.',
    effects: [block(8), discard()],
    upgradedEffects: [block(11), discard()],
  }),
  card({
    id: 'deadlyPoison',
    name: 'Deadly Poison',
    kind: 'skill',
    family: 'Poison',
    cost: 1,
    target: true,
    text: 'Apply 5 Poison.',
    upgradeText: 'Apply 7 Poison.',
    effects: [poison(5)],
    upgradedEffects: [poison(7)],
  }),
  card({
    id: 'poisonedStab',
    name: 'Poisoned Stab',
    kind: 'attack',
    family: 'Poison',
    cost: 1,
    target: true,
    text: 'Deal 6 damage. Apply 3 Poison.',
    upgradeText: 'Deal 8 damage. Apply 4 Poison.',
    effects: [hit(6), poison(3)],
    upgradedEffects: [hit(8), poison(4)],
  }),
  card({
    id: 'bladeDance',
    name: 'Blade Dance',
    kind: 'skill',
    family: 'Shivs',
    cost: 1,
    text: 'Add 3 Shivs to your hand.',
    upgradeText: 'Add 4 Shivs to your hand.',
    effects: [shivs(3)],
    upgradedEffects: [shivs(4)],
  }),
  card({
    id: 'cloakAndDagger',
    name: 'Cloak and Dagger',
    kind: 'skill',
    family: 'Shivs',
    cost: 1,
    text: 'Gain 6 Block. Add a Shiv to your hand.',
    upgradeText: 'Gain 6 Block. Add 2 Shivs.',
    effects: [block(6), shivs(1)],
    upgradedEffects: [block(6), shivs(2)],
  }),
  card({
    id: 'acrobatics',
    name: 'Acrobatics',
    kind: 'skill',
    family: 'Discard',
    cost: 1,
    text: 'Draw 3 cards. Discard 1.',
    upgradeText: 'Draw 4 cards. Discard 1.',
    effects: [draw(3), discard()],
    upgradedEffects: [draw(4), discard()],
  }),
  card({
    id: 'backflip',
    name: 'Backflip',
    kind: 'skill',
    cost: 1,
    text: 'Gain 5 Block. Draw 2.',
    upgradeText: 'Gain 8 Block. Draw 2.',
    effects: [block(5), draw(2)],
    upgradedEffects: [block(8), draw(2)],
  }),
  card({
    id: 'daggerThrow',
    name: 'Dagger Throw',
    kind: 'attack',
    family: 'Discard',
    cost: 1,
    target: true,
    text: 'Deal 9 damage. Draw 1, discard 1.',
    upgradeText: 'Deal 12 damage. Draw 1, discard 1.',
    effects: [hit(9), draw(1), discard()],
    upgradedEffects: [hit(12), draw(1), discard()],
  }),
  card({
    id: 'daggerSpray',
    name: 'Dagger Spray',
    kind: 'attack',
    cost: 1,
    text: 'Deal 4 damage to all enemies twice.',
    upgradeText: 'Deal 6 damage to all enemies twice.',
    effects: [{ type: 'damage', amount: 4, hits: 2, all: true }],
    upgradedEffects: [{ type: 'damage', amount: 6, hits: 2, all: true }],
  }),
  card({
    id: 'deflect',
    name: 'Deflect',
    kind: 'skill',
    cost: 0,
    text: 'Gain 4 Block.',
    upgradeText: 'Gain 7 Block.',
    effects: [block(4)],
    upgradedEffects: [block(7)],
  }),
  card({
    id: 'dodgeAndRoll',
    name: 'Dodge and Roll',
    kind: 'skill',
    cost: 1,
    text: 'Gain 4 Block now and next turn.',
    upgradeText: 'Gain 6 Block now and next turn.',
    effects: [block(4), { type: 'nextTurn', stat: 'block', amount: 4 }],
    upgradedEffects: [block(6), { type: 'nextTurn', stat: 'block', amount: 6 }],
  }),
  card({
    id: 'prepared',
    name: 'Prepared',
    kind: 'skill',
    family: 'Discard',
    cost: 0,
    text: 'Draw 1 card. Discard 1.',
    upgradeText: 'Draw 2 cards. Discard 2.',
    effects: [draw(1), discard()],
    upgradedEffects: [draw(2), discard(2)],
  }),
  card({
    id: 'suckerPunch',
    name: 'Sucker Punch',
    kind: 'attack',
    cost: 1,
    target: true,
    text: 'Deal 7 damage. Apply 1 Weak.',
    upgradeText: 'Deal 9 damage. Apply 2 Weak.',
    effects: [hit(7), weak(1)],
    upgradedEffects: [hit(9), weak(2)],
  }),
  card({
    id: 'quickSlash',
    name: 'Quick Slash',
    kind: 'attack',
    cost: 1,
    target: true,
    text: 'Deal 8 damage. Draw 1.',
    upgradeText: 'Deal 12 damage. Draw 1.',
    effects: [hit(8), draw(1)],
    upgradedEffects: [hit(12), draw(1)],
  }),
  card({
    id: 'slice',
    name: 'Slice',
    kind: 'attack',
    cost: 0,
    target: true,
    text: 'Deal 6 damage.',
    upgradeText: 'Deal 9 damage.',
    effects: [hit(6)],
    upgradedEffects: [hit(9)],
  }),
  card({
    id: 'bane',
    name: 'Bane',
    kind: 'attack',
    family: 'Poison',
    cost: 1,
    target: true,
    text: 'Deal 7 damage. If the enemy has Poison, hit again.',
    upgradeText: 'Deal 10 damage, twice if Poisoned.',
    effects: [{ type: 'damage', amount: 7, poisonedTwice: true }],
    upgradedEffects: [{ type: 'damage', amount: 10, poisonedTwice: true }],
  }),
  card({
    id: 'flyingKnee',
    name: 'Flying Knee',
    kind: 'attack',
    cost: 1,
    target: true,
    text: 'Deal 8 damage. Gain 1 Energy next turn.',
    upgradeText: 'Deal 11 damage. Gain 1 Energy next turn.',
    effects: [hit(8), { type: 'nextTurn', stat: 'energy', amount: 1 }],
    upgradedEffects: [hit(11), { type: 'nextTurn', stat: 'energy', amount: 1 }],
  }),
  card({
    id: 'footwork',
    name: 'Footwork',
    kind: 'power',
    rarity: 'uncommon',
    family: 'Defense',
    cost: 1,
    text: 'Gain 2 Dexterity.',
    upgradeText: 'Gain 3 Dexterity.',
    effects: [{ type: 'status', status: 'dexterity', amount: 2, target: 'self' }],
    upgradedEffects: [{ type: 'status', status: 'dexterity', amount: 3, target: 'self' }],
  }),
  card({
    id: 'noxiousFumes',
    name: 'Noxious Fumes',
    kind: 'power',
    rarity: 'uncommon',
    family: 'Poison',
    cost: 1,
    text: 'At the start of your turn, apply 2 Poison to all enemies.',
    upgradeText: 'Apply 3 Poison each turn.',
    effects: [power('noxiousFumes', 2)],
    upgradedEffects: [power('noxiousFumes', 3)],
  }),
  card({
    id: 'accuracy',
    name: 'Accuracy',
    kind: 'power',
    rarity: 'uncommon',
    family: 'Shivs',
    cost: 1,
    text: 'Shivs deal 4 additional damage.',
    upgradeText: 'Shivs deal 6 additional damage.',
    effects: [power('accuracy', 4)],
    upgradedEffects: [power('accuracy', 6)],
  }),
  card({
    id: 'infiniteBlades',
    name: 'Infinite Blades',
    kind: 'power',
    rarity: 'uncommon',
    family: 'Shivs',
    cost: 1,
    text: 'At the start of your turn, add a Shiv to your hand.',
    upgradeText: 'Innate. Add a Shiv each turn.',
    effects: [power('infiniteBlades', 1)],
    innateUpgrade: true,
  }),
  card({
    id: 'blur',
    name: 'Blur',
    kind: 'skill',
    rarity: 'uncommon',
    family: 'Defense',
    cost: 1,
    text: 'Gain 5 Block. Keep Block next turn.',
    upgradeText: 'Gain 8 Block. Keep Block next turn.',
    effects: [block(5), { type: 'blur', amount: 1 }],
    upgradedEffects: [block(8), { type: 'blur', amount: 1 }],
  }),
  card({
    id: 'legSweep',
    name: 'Leg Sweep',
    kind: 'skill',
    rarity: 'uncommon',
    family: 'Defense',
    cost: 2,
    target: true,
    text: 'Apply 2 Weak. Gain 11 Block.',
    upgradeText: 'Apply 3 Weak. Gain 14 Block.',
    effects: [weak(2), block(11)],
    upgradedEffects: [weak(3), block(14)],
  }),
  card({
    id: 'dash',
    name: 'Dash',
    kind: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: true,
    text: 'Gain 10 Block. Deal 10 damage.',
    upgradeText: 'Gain 13 Block. Deal 13 damage.',
    effects: [block(10), hit(10)],
    upgradedEffects: [block(13), hit(13)],
  }),
  card({
    id: 'catalyst',
    name: 'Catalyst',
    kind: 'skill',
    rarity: 'uncommon',
    family: 'Poison',
    cost: 1,
    target: true,
    exhaust: true,
    text: 'Double an enemy’s Poison. Exhaust.',
    upgradeText: 'Triple an enemy’s Poison. Exhaust.',
    effects: [{ type: 'multiplyPoison', amount: 2 }],
    upgradedEffects: [{ type: 'multiplyPoison', amount: 3 }],
  }),
  card({
    id: 'bouncingFlask',
    name: 'Bouncing Flask',
    kind: 'skill',
    rarity: 'uncommon',
    family: 'Poison',
    cost: 2,
    text: 'Apply 3 Poison to a random enemy 3 times.',
    upgradeText: 'Apply 3 Poison to a random enemy 4 times.',
    effects: [{ type: 'randomPoison', amount: 3, hits: 3 }],
    upgradedEffects: [{ type: 'randomPoison', amount: 3, hits: 4 }],
  }),
  card({
    id: 'cripplingCloud',
    name: 'Crippling Cloud',
    kind: 'skill',
    rarity: 'uncommon',
    family: 'Poison',
    cost: 2,
    exhaust: true,
    text: 'Apply 4 Poison and 2 Weak to all enemies. Exhaust.',
    upgradeText: 'Apply 7 Poison and 2 Weak to all enemies. Exhaust.',
    effects: [poison(4, true), weak(2, true)],
    upgradedEffects: [poison(7, true), weak(2, true)],
  }),
  card({
    id: 'calculatedGamble',
    name: 'Calculated Gamble',
    kind: 'skill',
    rarity: 'uncommon',
    family: 'Discard',
    cost: 0,
    exhaust: true,
    upgradedExhaust: false,
    text: 'Discard your hand. Draw that many cards. Exhaust.',
    upgradeText: 'Discard your hand. Draw that many cards. Does not Exhaust.',
    effects: [{ type: 'discardHand', draw: true }],
  }),
  card({
    id: 'concentrate',
    name: 'Concentrate',
    kind: 'skill',
    rarity: 'uncommon',
    family: 'Discard',
    cost: 0,
    text: 'Discard 3 cards. Gain 2 Energy.',
    upgradeText: 'Discard 2 cards. Gain 2 Energy.',
    effects: [discard(3), energy(2)],
    upgradedEffects: [discard(2), energy(2)],
  }),
  card({
    id: 'reflex',
    name: 'Reflex',
    kind: 'skill',
    rarity: 'uncommon',
    family: 'Discard',
    cost: -1,
    text: 'Unplayable. When discarded by a card, draw 2.',
    upgradeText: 'When discarded by a card, draw 3.',
    effects: [],
    onDiscard: { type: 'draw', amount: 2, upgradedAmount: 3 },
  }),
  card({
    id: 'tactician',
    name: 'Tactician',
    kind: 'skill',
    rarity: 'uncommon',
    family: 'Discard',
    cost: -1,
    text: 'Unplayable. When discarded by a card, gain 1 Energy.',
    upgradeText: 'When discarded by a card, gain 2 Energy.',
    effects: [],
    onDiscard: { type: 'energy', amount: 1, upgradedAmount: 2 },
  }),
  card({
    id: 'sneakyStrike',
    name: 'Sneaky Strike',
    kind: 'attack',
    family: 'Discard',
    cost: 2,
    target: true,
    requiresDiscard: true,
    text: 'Deal 12 damage. If you discarded this turn, gain 2 Energy.',
    upgradeText: 'Deal 16 damage. Same Energy refund.',
    effects: [hit(12)],
    upgradedEffects: [hit(16)],
  }),
  card({
    id: 'adrenaline',
    name: 'Adrenaline',
    kind: 'skill',
    rarity: 'rare',
    cost: 0,
    exhaust: true,
    text: 'Gain 1 Energy. Draw 2. Exhaust.',
    upgradeText: 'Gain 2 Energy. Draw 2. Exhaust.',
    effects: [energy(1), draw(2)],
    upgradedEffects: [energy(2), draw(2)],
  }),
  card({
    id: 'afterImage',
    name: 'After Image',
    kind: 'power',
    rarity: 'rare',
    family: 'Defense',
    cost: 1,
    text: 'Whenever you play a card, gain 1 Block.',
    upgradeText: 'Innate. Gain 1 Block whenever you play a card.',
    effects: [power('afterImage', 1)],
    innateUpgrade: true,
  }),
  card({
    id: 'envenom',
    name: 'Envenom',
    kind: 'power',
    rarity: 'rare',
    family: 'Poison',
    cost: 2,
    upgradedCost: 1,
    text: 'Whenever an Attack deals unblocked damage, apply 1 Poison.',
    upgradeText: 'Costs 1. Apply 1 Poison per unblocked Attack hit.',
    effects: [power('envenom', 1)],
  }),
  card({
    id: 'thousandCuts',
    name: 'A Thousand Cuts',
    kind: 'power',
    rarity: 'rare',
    cost: 2,
    text: 'Whenever you play a card, deal 1 damage to all enemies.',
    upgradeText: 'Deal 2 damage to all enemies per card.',
    effects: [power('thousandCuts', 1)],
    upgradedEffects: [power('thousandCuts', 2)],
  }),
  card({
    id: 'dieDieDie',
    name: 'Die Die Die',
    kind: 'attack',
    rarity: 'rare',
    cost: 1,
    exhaust: true,
    text: 'Deal 13 damage to all enemies. Exhaust.',
    upgradeText: 'Deal 17 damage to all enemies. Exhaust.',
    effects: [hit(13, true)],
    upgradedEffects: [hit(17, true)],
  }),
  card({
    id: 'shiv',
    name: 'Shiv',
    kind: 'attack',
    rarity: 'special',
    family: 'Shivs',
    cost: 0,
    target: true,
    exhaust: true,
    token: true,
    text: 'Deal 4 damage. Exhaust.',
    upgradeText: 'Deal 6 damage. Exhaust.',
    effects: [hit(4)],
    upgradedEffects: [hit(6)],
  }),
];
