import type {
  EnemyDefinition,
  EnemyEffect,
  Intent,
  RelicDefinition,
  Potion,
} from '../domain/types';
const hit = (amount: number, hits = 1): EnemyEffect => ({ type: 'damage', amount, hits });
const block = (amount: number): EnemyEffect => ({ type: 'block', amount });
const debuff = (
  status: 'weak' | 'vulnerable' | 'frail' | 'strength' | 'dexterity',
  amount: number,
): EnemyEffect => ({ type: 'status', status, amount, target: 'enemy' });
const strength = (amount: number): EnemyEffect => ({
  type: 'status',
  status: 'strength',
  amount,
  target: 'self',
});
const special = (action: string, amount = 0): EnemyEffect => ({ type: 'special', action, amount });
const junk = (card: string, amount: number): EnemyEffect => ({
  type: 'generate',
  card,
  amount,
  zone: 'discard',
});
const move = (name: string, ...effects: EnemyEffect[]): Intent => ({ name, effects });
export const ACT_NAMES = ['The Exordium', 'The City', 'The Beyond'];
export const BOSS_ENCOUNTERS = [['slimeBoss'], ['champ'], ['donu', 'deca']];
export const ENEMIES: EnemyDefinition[] = [
  {
    id: 'cultist',
    name: 'Cultist',
    symbol: '♟',
    hp: 50,
    act: 1,
    kind: 'normal',
    behavior: 'cultist',
    description: 'Gains Ritual, then grows stronger after each attack.',
    intents: [move('Incantation', special('ritual', 3)), move('Dark Strike', hit(6))],
  },
  {
    id: 'jawWorm',
    name: 'Jaw Worm',
    symbol: '◒',
    hp: 42,
    act: 1,
    kind: 'normal',
    behavior: 'jawWorm',
    description: 'Mixes attacks, Block and permanent Strength.',
    intents: [
      move('Chomp', hit(11)),
      move('Thrash', hit(7), block(5)),
      move('Bellow', strength(3), block(6)),
    ],
  },
  {
    id: 'redLouse',
    name: 'Red Louse',
    symbol: '◉',
    hp: 14,
    act: 1,
    kind: 'normal',
    behavior: 'louse',
    description: 'Curl Up grants 6 Block after the first attack that wounds it.',
    intents: [move('Bite', hit(6)), move('Grow', strength(3))],
  },
  {
    id: 'greenLouse',
    name: 'Green Louse',
    symbol: '◉',
    hp: 13,
    act: 1,
    kind: 'normal',
    behavior: 'louse',
    description: 'Curl Up once; can apply Weak.',
    intents: [move('Bite', hit(5)), move('Spit Web', debuff('weak', 2))],
  },
  {
    id: 'acidSlimeM',
    name: 'Acid Slime (M)',
    symbol: '●',
    hp: 30,
    act: 1,
    kind: 'normal',
    behavior: 'slime',
    description: 'Adds Slimed cards and Weak.',
    intents: [
      move('Corrosive Spit', hit(7), junk('slimed', 1)),
      move('Tackle', hit(10)),
      move('Lick', debuff('weak', 1)),
    ],
  },
  {
    id: 'spikeSlimeM',
    name: 'Spike Slime (M)',
    symbol: '▲',
    hp: 30,
    act: 1,
    kind: 'normal',
    behavior: 'slime',
    description: 'Adds Slimed cards and Frail.',
    intents: [move('Flame Tackle', hit(8), junk('slimed', 1)), move('Lick', debuff('frail', 1))],
  },
  {
    id: 'acidSlimeL',
    name: 'Acid Slime (L)',
    symbol: '●',
    hp: 68,
    act: 1,
    kind: 'normal',
    behavior: 'splitAcid',
    description: 'At half HP, interrupts its next move to split into two medium Slimes.',
    intents: [
      move('Corrosive Spit', hit(11), junk('slimed', 2)),
      move('Tackle', hit(16)),
      move('Lick', debuff('weak', 2)),
      move('Split', special('splitAcid')),
    ],
  },
  {
    id: 'spikeSlimeL',
    name: 'Spike Slime (L)',
    symbol: '▲',
    hp: 67,
    act: 1,
    kind: 'normal',
    behavior: 'splitSpike',
    description: 'At half HP, splits. Each child inherits current HP.',
    intents: [
      move('Flame Tackle', hit(16), junk('slimed', 2)),
      move('Lick', debuff('frail', 2)),
      move('Split', special('splitSpike')),
    ],
  },
  {
    id: 'gremlinNob',
    name: 'Gremlin Nob',
    symbol: '♜',
    hp: 85,
    act: 1,
    kind: 'elite',
    behavior: 'nob',
    description: 'After Bellow, each Skill you play gives Nob 2 Strength.',
    intents: [
      move('Bellow', special('enrage', 2)),
      move('Rush', hit(14)),
      move('Skull Bash', hit(6), debuff('vulnerable', 2)),
    ],
  },
  {
    id: 'lagavulin',
    name: 'Lagavulin',
    symbol: '⬡',
    hp: 111,
    act: 1,
    kind: 'elite',
    behavior: 'lagavulin',
    block: 8,
    description:
      'Sleeps for up to three turns or until wounded; then attacks and drains Strength/Dexterity.',
    intents: [
      move('Sleep', block(8)),
      move('Attack', hit(18)),
      move('Siphon Soul', debuff('strength', -1), debuff('dexterity', -1)),
    ],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    symbol: '▣',
    hp: 40,
    act: 1,
    kind: 'elite',
    artifact: 1,
    behavior: 'sentry',
    description: 'Artifact blocks one debuff. Alternates 9 damage with two Dazed.',
    intents: [move('Beam', hit(9)), move('Bolt', junk('dazed', 2))],
  },
  {
    id: 'slimeBoss',
    name: 'Slime Boss',
    symbol: '♛',
    hp: 140,
    act: 1,
    kind: 'boss',
    behavior: 'slimeBoss',
    description: 'Prepare for 35 damage on turn three, or force a split at half HP.',
    intents: [
      move('Goop Spray', junk('slimed', 3)),
      move('Preparing'),
      move('Slam', hit(35)),
      move('Split', special('splitBoss')),
    ],
  },
  {
    id: 'chosen',
    name: 'Chosen',
    symbol: '☥',
    hp: 98,
    act: 2,
    kind: 'normal',
    behavior: 'chosen',
    description: 'Hex adds a Dazed to draw whenever you play a non-Attack.',
    intents: [
      move('Poke', hit(5, 2)),
      move('Hex', special('hex')),
      move('Debilitate', hit(10), debuff('vulnerable', 2)),
      move('Drain', debuff('weak', 3), strength(3)),
      move('Zap', hit(18)),
    ],
  },
  {
    id: 'centurion',
    name: 'Centurion',
    symbol: '♜',
    hp: 80,
    act: 2,
    kind: 'normal',
    behavior: 'centurion',
    description: 'Protects the Mystic; uses Fury after its ally falls.',
    intents: [
      move('Slash', hit(12)),
      move('Defend', special('allyBlock', 15)),
      move('Fury', hit(6, 3)),
    ],
  },
  {
    id: 'mystic',
    name: 'Mystic',
    symbol: '✧',
    hp: 52,
    act: 2,
    kind: 'normal',
    behavior: 'mystic',
    description: 'Heals wounded allies, buffs Strength, or attacks with Frail.',
    intents: [
      move('Heal', special('healAll', 16)),
      move('Buff', special('allyStrength', 2)),
      move('Attack', hit(8), debuff('frail', 2)),
    ],
  },
  {
    id: 'sphericGuardian',
    name: 'Spheric Guardian',
    symbol: '◉',
    hp: 20,
    act: 2,
    kind: 'normal',
    behavior: 'sphere',
    artifact: 3,
    block: 40,
    description: 'Keeps Block between turns. Artifact blocks its first three debuffs.',
    intents: [
      move('Activate', block(25)),
      move('Attack', hit(10), debuff('frail', 5)),
      move('Slam', hit(10, 2)),
      move('Harden', hit(10), block(15)),
    ],
  },
  {
    id: 'snakePlant',
    name: 'Snake Plant',
    symbol: '❦',
    hp: 78,
    act: 2,
    kind: 'normal',
    behavior: 'snakePlant',
    description: 'Malleable gains increasing Block after each attack hit.',
    intents: [
      move('Chomp', hit(7, 3)),
      move('Enfeebling Spores', debuff('weak', 2), debuff('frail', 2)),
    ],
  },
  {
    id: 'bookOfStabbing',
    name: 'Book of Stabbing',
    symbol: '▤',
    hp: 165,
    act: 2,
    kind: 'elite',
    behavior: 'book',
    description: 'Multi-Stab gains hits. Every hit that removes HP adds a Wound.',
    intents: [move('Multi-Stab', hit(6, 2)), move('Single Stab', hit(21))],
  },
  {
    id: 'taskmaster',
    name: 'Taskmaster',
    symbol: '⚑',
    hp: 57,
    act: 2,
    kind: 'elite',
    behavior: 'cycle',
    description: 'Whip adds a Wound to your discard pile.',
    intents: [move('Scouring Whip', hit(7), junk('wound', 1))],
  },
  {
    id: 'slaverRed',
    name: 'Red Slaver',
    symbol: '⚔',
    hp: 50,
    act: 2,
    kind: 'elite',
    behavior: 'redSlaver',
    description: 'Applies Vulnerable and can prevent Attacks for one turn.',
    intents: [
      move('Stab', hit(13)),
      move('Scrape', hit(8), debuff('vulnerable', 1)),
      move('Entangle', special('entangle')),
    ],
  },
  {
    id: 'slaverBlue',
    name: 'Blue Slaver',
    symbol: '⚔',
    hp: 50,
    act: 2,
    kind: 'elite',
    behavior: 'slaver',
    description: 'Mixes attacks with Weak.',
    intents: [move('Stab', hit(12)), move('Rake', hit(7), debuff('weak', 1))],
  },
  {
    id: 'champ',
    name: 'The Champ',
    symbol: '♛',
    hp: 420,
    act: 2,
    kind: 'boss',
    behavior: 'champ',
    description: 'At half HP, cleanses debuffs and gains Strength; Execute follows next turn.',
    intents: [
      move('Heavy Slash', hit(16)),
      move('Defensive Stance', block(15), special('metallicize', 5)),
      move('Face Slap', hit(12), debuff('frail', 2), debuff('vulnerable', 2)),
      move('Taunt', debuff('weak', 2), debuff('vulnerable', 2)),
      move('Anger', special('cleanse'), strength(6)),
      move('Execute', hit(10, 2)),
    ],
  },
  {
    id: 'spiker',
    name: 'Spiker',
    symbol: '✹',
    hp: 50,
    act: 3,
    kind: 'normal',
    behavior: 'spiker',
    description: 'Thorns retaliates on every Attack hit, even through Block.',
    intents: [move('Cut', hit(7)), move('Spike', special('thorns', 2))],
  },
  {
    id: 'repulsor',
    name: 'Repulsor',
    symbol: '◌',
    hp: 33,
    act: 3,
    kind: 'normal',
    behavior: 'repulsor',
    description: 'Fills the deck with Dazed.',
    intents: [move('Bash', hit(11)), move('Repulse', junk('dazed', 2))],
  },
  {
    id: 'exploder',
    name: 'Exploder',
    symbol: '✸',
    hp: 30,
    act: 3,
    kind: 'normal',
    behavior: 'exploder',
    description: 'Explodes for 30 on turn three, then destroys itself.',
    intents: [move('Slam', hit(9)), move('Explode', hit(30), special('selfDestruct'))],
  },
  {
    id: 'orbWalker',
    name: 'Orb Walker',
    symbol: '◈',
    hp: 94,
    act: 3,
    kind: 'normal',
    behavior: 'orb',
    description: 'Gains 3 Strength per turn and adds Burns.',
    intents: [move('Laser', hit(10), junk('burn', 2)), move('Claw', hit(15))],
  },
  {
    id: 'spireGrowth',
    name: 'Spire Growth',
    symbol: '♧',
    hp: 170,
    act: 3,
    kind: 'normal',
    behavior: 'growth',
    description: 'Constrict deals 10 blockable damage at your turn end.',
    intents: [
      move('Quick Tackle', hit(16)),
      move('Constrict', special('constrict', 10)),
      move('Smash', hit(22)),
    ],
  },
  {
    id: 'giantHead',
    name: 'Giant Head',
    symbol: '☗',
    hp: 500,
    act: 3,
    kind: 'elite',
    behavior: 'giantHead',
    description:
      'Slow adds 10% attack damage per card played this turn. A heavy countdown ends on turn five.',
    intents: [
      move('Count', hit(13)),
      move('Glare', debuff('weak', 1)),
      move('It Is Time', hit(30)),
    ],
  },
  {
    id: 'nemesis',
    name: 'Nemesis',
    symbol: '☠',
    hp: 185,
    act: 3,
    kind: 'elite',
    behavior: 'nemesis',
    description: 'Alternates Intangible turns, reducing each incoming damage instance to 1.',
    intents: [move('Attack', hit(6, 3)), move('Scythe', hit(45)), move('Debuff', junk('burn', 3))],
  },
  {
    id: 'donu',
    name: 'Donu',
    symbol: '◎',
    hp: 250,
    act: 3,
    kind: 'boss',
    behavior: 'donu',
    artifact: 2,
    description: 'Alternates party-wide +3 Strength with a double attack.',
    intents: [move('Circle of Power', special('allyStrength', 3)), move('Beam', hit(10, 2))],
  },
  {
    id: 'deca',
    name: 'Deca',
    symbol: '⬟',
    hp: 250,
    act: 3,
    kind: 'boss',
    behavior: 'deca',
    artifact: 2,
    description: 'Alternates a double attack plus Dazed with party-wide Block.',
    intents: [
      move('Beam', hit(10, 2), junk('dazed', 2)),
      move('Square of Protection', special('allyBlock', 16)),
    ],
  },
];
export const ENEMY_BY_ID = Object.fromEntries(ENEMIES.map((e) => [e.id, e])) as Record<
  string,
  EnemyDefinition
>;
export const RELICS: RelicDefinition[] = [
  {
    id: 'burningBlood',
    name: 'Burning Blood',
    symbol: '♥',
    rarity: 'starter',
    text: 'After combat, heal 6 HP.',
  },
  {
    id: 'vajra',
    name: 'Vajra',
    symbol: '⚒',
    rarity: 'common',
    text: 'Begin combat with 1 Strength.',
  },
  {
    id: 'oddlySmoothStone',
    name: 'Oddly Smooth Stone',
    symbol: '●',
    rarity: 'common',
    text: 'Begin combat with 1 Dexterity.',
  },
  {
    id: 'anchor',
    name: 'Anchor',
    symbol: '⚓',
    rarity: 'common',
    text: 'Begin combat with 10 Block.',
  },
  {
    id: 'lantern',
    name: 'Lantern',
    symbol: '☀',
    rarity: 'common',
    text: 'Gain 1 extra Energy on the first turn.',
  },
  {
    id: 'bagOfPreparation',
    name: 'Bag of Preparation',
    symbol: '▱',
    rarity: 'common',
    text: 'Draw 2 additional cards on the first turn.',
  },
  {
    id: 'bagOfMarbles',
    name: 'Bag of Marbles',
    symbol: '◌',
    rarity: 'common',
    text: 'Apply 1 Vulnerable to all enemies at combat start.',
  },
  {
    id: 'orichalcum',
    name: 'Orichalcum',
    symbol: '⬡',
    rarity: 'common',
    text: 'If you end your turn with 0 Block, gain 6 Block.',
  },
  {
    id: 'akabeko',
    name: 'Akabeko',
    symbol: '♉',
    rarity: 'common',
    text: 'Your first Attack each combat gains 8 damage per hit.',
  },
  {
    id: 'penNib',
    name: 'Pen Nib',
    symbol: '✒',
    rarity: 'common',
    text: 'Every tenth Attack played deals double damage. Counter persists.',
  },
  {
    id: 'bronzeScales',
    name: 'Bronze Scales',
    symbol: '♠',
    rarity: 'common',
    text: 'When attacked, retaliate for 3 damage per hit.',
  },
  {
    id: 'happyFlower',
    name: 'Happy Flower',
    symbol: '✿',
    rarity: 'common',
    text: 'Every third player turn, gain 1 Energy. Counter persists.',
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    symbol: '♥',
    rarity: 'common',
    text: 'Gain 7 maximum HP on pickup.',
  },
  {
    id: 'warPaint',
    name: 'War Paint',
    symbol: '▥',
    rarity: 'common',
    text: 'Upgrade 2 random Skills in your permanent deck on pickup.',
  },
  {
    id: 'whetstone',
    name: 'Whetstone',
    symbol: '▲',
    rarity: 'common',
    text: 'Upgrade 2 random Attacks in your permanent deck on pickup.',
  },
  {
    id: 'regalPillow',
    name: 'Regal Pillow',
    symbol: '▰',
    rarity: 'common',
    text: 'Rest heals 15 additional HP.',
  },
  {
    id: 'preservedInsect',
    name: 'Preserved Insect',
    symbol: '✧',
    rarity: 'common',
    text: 'Elite enemies start with 25% less HP.',
  },
  {
    id: 'kunai',
    name: 'Kunai',
    symbol: '➶',
    rarity: 'uncommon',
    text: 'Every 3 Attacks played in one turn, gain 1 Dexterity.',
  },
  {
    id: 'shuriken',
    name: 'Shuriken',
    symbol: '✦',
    rarity: 'uncommon',
    text: 'Every 3 Attacks played in one turn, gain 1 Strength.',
  },
  {
    id: 'ornamentalFan',
    name: 'Ornamental Fan',
    symbol: '◔',
    rarity: 'uncommon',
    text: 'Every 3 Attacks played in one turn, gain 4 Block.',
  },
  {
    id: 'meatOnTheBone',
    name: 'Meat on the Bone',
    symbol: '♧',
    rarity: 'uncommon',
    text: 'After combat, heal 12 HP if at or below half maximum HP.',
  },
  {
    id: 'letterOpener',
    name: 'Letter Opener',
    symbol: '†',
    rarity: 'uncommon',
    text: 'Every 3 Skills played in one turn, deal 5 damage to all enemies.',
  },
  {
    id: 'pear',
    name: 'Pear',
    symbol: '♧',
    rarity: 'uncommon',
    text: 'Gain 10 maximum HP on pickup.',
  },
  {
    id: 'mango',
    name: 'Mango',
    symbol: '◕',
    rarity: 'rare',
    text: 'Gain 14 maximum HP on pickup.',
  },
  {
    id: 'blackBlood',
    name: 'Black Blood',
    symbol: '♥',
    rarity: 'boss',
    text: 'Replaces Burning Blood. Heal 12 HP after combat.',
  },
  {
    id: 'coffeeDripper',
    name: 'Coffee Dripper',
    symbol: '♨',
    rarity: 'boss',
    text: '+1 Energy per turn. Resting at campfires is disabled.',
  },
  {
    id: 'fusionHammer',
    name: 'Fusion Hammer',
    symbol: '⚒',
    rarity: 'boss',
    text: '+1 Energy per turn. Smithing at campfires is disabled.',
  },
  {
    id: 'cursedKey',
    name: 'Cursed Key',
    symbol: '⚿',
    rarity: 'boss',
    text: '+1 Energy per turn. Opening a treasure chest adds a Curse.',
  },
  {
    id: 'sozu',
    name: 'Sozu',
    symbol: '〰',
    rarity: 'boss',
    text: '+1 Energy per turn. You cannot obtain potions.',
  },
  {
    id: 'bustedCrown',
    name: 'Busted Crown',
    symbol: '♛',
    rarity: 'boss',
    text: '+1 Energy per turn. Card rewards offer 2 fewer cards.',
  },
  {
    id: 'neowsLament',
    name: 'Neow’s Lament',
    symbol: '◈',
    rarity: 'event',
    text: 'Enemies in the first three combats have 1 HP.',
  },
  {
    id: 'goldenIdol',
    name: 'Golden Idol',
    symbol: '♙',
    rarity: 'event',
    text: 'Gain 25% more combat gold.',
  },
];
export const RELIC_BY_ID = Object.fromEntries(RELICS.map((r) => [r.id, r])) as Record<
  string,
  RelicDefinition
>;
export const ENERGY_RELICS = ['coffeeDripper', 'fusionHammer', 'cursedKey', 'sozu', 'bustedCrown'];
export const POTIONS: Record<
  Potion,
  { name: string; text: string; symbol: string; target?: boolean }
> = {
  fire: {
    name: 'Fire Potion',
    text: 'Deal 20 non-Attack damage to one enemy. Block applies.',
    symbol: '♨',
    target: true,
  },
  block: { name: 'Block Potion', text: 'Gain 12 Block.', symbol: '⬡' },
  strength: { name: 'Strength Potion', text: 'Gain 2 Strength this combat.', symbol: '✦' },
  dexterity: { name: 'Dexterity Potion', text: 'Gain 2 Dexterity this combat.', symbol: '◇' },
  energy: { name: 'Energy Potion', text: 'Gain 2 Energy this turn.', symbol: 'ϟ' },
  blood: { name: 'Blood Potion', text: 'Heal 20% maximum HP.', symbol: '♥' },
  explosive: {
    name: 'Explosive Potion',
    text: 'Deal 10 non-Attack damage to every enemy.',
    symbol: '✹',
  },
  weak: { name: 'Weak Potion', text: 'Apply 3 Weak to one enemy.', symbol: '≈', target: true },
};
