import { isFace } from '../domain/poker';
import type { JokerDefinition, Suit } from '../domain/types';

type Draft = Pick<JokerDefinition, 'id' | 'name' | 'description' | 'symbol'> &
  Partial<Omit<JokerDefinition, 'id' | 'name' | 'description' | 'symbol'>>;
const joker = (definition: Draft): JokerDefinition => ({
  family: 'Foundation',
  rarity: 'common',
  price: 5,
  ...definition,
});
const suitJoker = (suit: Suit, name: string, symbol: string) =>
  joker({
    id: suit,
    name,
    symbol,
    family: 'Suits',
    description: `Each scored ${suit} card gives +4 mult. Wild cards qualify.`,
    onCard: (_, card) =>
      card.suit === suit || card.enhancement === 'wild' ? { mult: 4 } : undefined,
  });

/** Small pure hooks are the modding API. Context is read-only; return an effect. */
export const JOKERS: JokerDefinition[] = [
  joker({
    id: 'spark',
    name: 'Spark',
    symbol: '✳',
    description: '+4 mult.',
    onHand: () => ({ mult: 4 }),
  }),
  joker({
    id: 'granite',
    name: 'Granite',
    symbol: '▰',
    description: '+50 chips.',
    onHand: () => ({ chips: 50 }),
  }),
  joker({
    id: 'duet',
    name: 'Duet',
    symbol: 'Ⅱ',
    family: 'Pairs',
    description: '+8 mult if the hand contains a pair.',
    onHand: (c) => (c.poker.hasPair ? { mult: 8 } : undefined),
  }),
  joker({
    id: 'twins',
    name: 'Double Take',
    symbol: '◫',
    family: 'Pairs',
    description: '+80 chips for Two Pair or Full House.',
    onHand: (c) =>
      ['twoPair', 'fullHouse', 'flushHouse'].includes(c.poker.type) ? { chips: 80 } : undefined,
  }),
  joker({
    id: 'trio',
    name: 'Trio',
    symbol: 'Ⅲ',
    family: 'Pairs',
    description: '+16 mult if the hand contains three of a kind.',
    onHand: (c) => (c.poker.hasThree ? { mult: 16 } : undefined),
  }),
  joker({
    id: 'stair',
    name: 'Stairway',
    symbol: '▤',
    family: 'Straights',
    description: '+18 mult for a Straight or Straight Flush.',
    onHand: (c) => (c.poker.hasStraight ? { mult: 18 } : undefined),
  }),
  joker({
    id: 'river',
    name: 'Riverbed',
    symbol: '≈',
    family: 'Suits',
    description: '+14 mult for any five-card flush.',
    onHand: (c) => (c.poker.hasFlush ? { mult: 14 } : undefined),
  }),
  joker({
    id: 'house',
    name: 'Open House',
    symbol: '⌂',
    family: 'Pairs',
    description: '+24 mult for Full House or Flush House.',
    onHand: (c) => (['fullHouse', 'flushHouse'].includes(c.poker.type) ? { mult: 24 } : undefined),
  }),
  joker({
    id: 'crown',
    name: 'Fourfold',
    symbol: '♛',
    family: 'Pairs',
    rarity: 'rare',
    price: 8,
    description: '×3 mult if the hand contains four of a kind.',
    onHand: (c) => (c.poker.hasFour ? { factor: 3 } : undefined),
  }),
  joker({
    id: 'constellation',
    name: 'Constellation',
    symbol: '✧',
    family: 'Straights',
    rarity: 'rare',
    price: 9,
    description: '×4 mult for Straight Flush.',
    onHand: (c) => (c.poker.type === 'straightFlush' ? { factor: 4 } : undefined),
  }),
  suitJoker('hearts', 'Heartwood', '♥'),
  suitJoker('diamonds', 'Prism', '♦'),
  suitJoker('clubs', 'Clover', '♣'),
  suitJoker('spades', 'Nightfall', '♠'),
  joker({
    id: 'portrait',
    name: 'Portrait',
    symbol: '▧',
    family: 'Ranks',
    description: 'Each scored J, Q or K gives +5 mult.',
    onCard: (_, card) => (isFace(card) ? { mult: 5 } : undefined),
  }),
  joker({
    id: 'even',
    name: 'Even Keel',
    symbol: '＝',
    family: 'Ranks',
    description: 'Scored 2, 4, 6, 8 and 10 each give +24 chips.',
    onCard: (_, card) => (card.rank <= 10 && card.rank % 2 === 0 ? { chips: 24 } : undefined),
  }),
  joker({
    id: 'odd',
    name: 'Odd Company',
    symbol: '≠',
    family: 'Ranks',
    description: 'Scored A, 3, 5, 7 and 9 each give +4 mult.',
    onCard: (_, card) => ([14, 3, 5, 7, 9].includes(card.rank) ? { mult: 4 } : undefined),
  }),
  joker({
    id: 'fibonacci',
    name: 'Spiral',
    symbol: '◎',
    family: 'Ranks',
    rarity: 'uncommon',
    price: 6,
    description: 'Scored A, 2, 3, 5 and 8 each give +6 mult.',
    onCard: (_, card) => ([14, 2, 3, 5, 8].includes(card.rank) ? { mult: 6 } : undefined),
  }),
  joker({
    id: 'ace',
    name: 'Ace High',
    symbol: 'A',
    family: 'Ranks',
    description: 'Each scored Ace gives +40 chips.',
    onCard: (_, card) => (card.rank === 14 ? { chips: 40 } : undefined),
  }),
  joker({
    id: 'low',
    name: 'Small Wonders',
    symbol: '⋆',
    family: 'Ranks',
    description: 'Scored 2–5 each give +20 chips.',
    onCard: (_, card) => (card.rank <= 5 ? { chips: 20 } : undefined),
  }),
  joker({
    id: 'solo',
    name: 'Soloist',
    symbol: 'Ⅰ',
    family: 'Small hands',
    description: '+20 mult when only one card is played.',
    onHand: (c) => (c.played.length === 1 ? { mult: 20 } : undefined),
  }),
  joker({
    id: 'minimal',
    name: 'Less Is More',
    symbol: '−',
    family: 'Small hands',
    description: '+14 mult when at most three cards are played.',
    onHand: (c) => (c.played.length <= 3 ? { mult: 14 } : undefined),
  }),
  joker({
    id: 'banquet',
    name: 'Banquet',
    symbol: '▦',
    description: '+80 chips when five cards are played.',
    onHand: (c) => (c.played.length === 5 ? { chips: 80 } : undefined),
  }),
  joker({
    id: 'rainy',
    name: 'Rainy Day',
    symbol: '☂',
    family: 'Economy',
    description: '+4 mult per discard remaining.',
    onHand: (c) => ({ mult: c.run.discardsLeft * 4 }),
  }),
  joker({
    id: 'last',
    name: 'Last Word',
    symbol: '!',
    rarity: 'uncommon',
    price: 6,
    description: '×3 mult on your last available hand.',
    onHand: (c) => (c.run.handsLeft === 1 ? { factor: 3 } : undefined),
  }),
  joker({
    id: 'bankroll',
    name: 'Nest Egg',
    symbol: '◉',
    family: 'Economy',
    rarity: 'uncommon',
    price: 7,
    description: '×2.5 mult while holding at least $25.',
    onHand: (c) => (c.run.cash >= 25 ? { factor: 2.5 } : undefined),
  }),
  joker({
    id: 'purse',
    name: 'Deep Pockets',
    symbol: '$',
    family: 'Economy',
    description: '+2 mult per $5 held (maximum +40).',
    onHand: (c) => ({ mult: Math.min(40, Math.floor(c.run.cash / 5) * 2) }),
  }),
  joker({
    id: 'scholar',
    name: 'Scholar',
    symbol: '✎',
    family: 'Scaling',
    description: '+25 chips per level of the played hand.',
    onHand: (c) => ({ chips: c.run.levels[c.poker.type] * 25 }),
  }),
  joker({
    id: 'collector',
    name: 'Collector',
    symbol: '⊞',
    family: 'Deck shaping',
    description: '+35 chips per card above 52 in your deck.',
    onHand: (c) => ({ chips: Math.max(0, c.run.deck.length - 52) * 35 }),
  }),
  joker({
    id: 'sculptor',
    name: 'Sculptor',
    symbol: '◇',
    family: 'Deck shaping',
    description: '+5 mult per card below 52 in your deck.',
    onHand: (c) => ({ mult: Math.max(0, 52 - c.run.deck.length) * 5 }),
  }),
  joker({
    id: 'runner',
    name: 'Long Distance',
    symbol: '↗',
    family: 'Straights',
    rarity: 'uncommon',
    price: 6,
    description: 'Starts at +30 chips. Gains +35 chips after each scoring Straight.',
    onHand: (_, j) => ({ chips: 30 + j.growth }),
    grow: (c) => (c.poker.hasStraight ? 35 : 0),
  }),
  joker({
    id: 'vine',
    name: 'Climbing Vine',
    symbol: '❧',
    family: 'Scaling',
    rarity: 'uncommon',
    price: 6,
    description: 'Starts at +2 mult. Gains +2 mult after every scoring hand.',
    onHand: (_, j) => ({ mult: 2 + j.growth }),
    grow: () => 2,
  }),
  joker({
    id: 'paircraft',
    name: 'Familiar Faces',
    symbol: '∞',
    family: 'Pairs',
    rarity: 'uncommon',
    price: 6,
    description: 'Starts at +2 mult. Gains +3 mult after each scoring hand containing a pair.',
    onHand: (_, j) => ({ mult: 2 + j.growth }),
    grow: (c) => (c.poker.hasPair ? 3 : 0),
  }),
  joker({
    id: 'tidal',
    name: 'Rising Tide',
    symbol: '≋',
    family: 'Suits',
    rarity: 'rare',
    price: 8,
    description: 'Starts at ×1 mult. Gains ×0.2 after each scoring flush.',
    onHand: (_, j) => ({ factor: 1 + j.growth / 10 }),
    grow: (c) => (c.poker.hasFlush ? 2 : 0),
  }),
  joker({
    id: 'toll',
    name: 'Side Hustle',
    symbol: '¢',
    family: 'Economy',
    description: 'Earn $2 for every scoring hand.',
    onHand: () => ({ cash: 2 }),
  }),
  joker({
    id: 'dividend',
    name: 'Dividend',
    symbol: '%',
    family: 'Economy',
    price: 6,
    description: 'Earn $5 when a blind is defeated.',
    income: () => 5,
  }),
  joker({
    id: 'reserve',
    name: 'Second Wind',
    symbol: '↻',
    description: '+1 hand at the start of each blind.',
    rule: 'extraHand',
  }),
  joker({
    id: 'satchel',
    name: 'Room to Think',
    symbol: '▱',
    description: '+1 hand size, including the current blind.',
    rule: 'extraCard',
  }),
  joker({
    id: 'echo',
    name: 'Little Echo',
    symbol: '»',
    family: 'Ranks',
    rarity: 'rare',
    price: 8,
    description: 'Retrigger each scored 2–5 once, including its enhancement and card hooks.',
    rule: 'repeatLow',
  }),
  joker({
    id: 'splash',
    name: 'Everyone In',
    symbol: '✺',
    rarity: 'uncommon',
    price: 6,
    description: 'Every played card scores, including kickers.',
    rule: 'allScore',
  }),
];

export const JOKER_BY_ID = Object.fromEntries(JOKERS.map((item) => [item.id, item])) as Record<
  string,
  JokerDefinition
>;
